-- ==========================================================================
-- Part 1 of 3 - the tables
--
-- Creates all 34 tables.
-- Run this first.
--
-- HOW TO RUN THIS
--   1. Open your Supabase project.
--   2. Click the SQL Editor icon in the far-left sidebar.
--   3. Click 'New query'.
--   4. Paste this whole file in.
--   5. Click 'Run' (or press Ctrl+Enter).
--
-- It is safe to run more than once. If you are not sure whether it worked,
-- just run it again -- nothing is duplicated and nothing is lost.
--
-- Generated from: db/migrations/001_extensions.sql, db/migrations/002_identity.sql, db/migrations/003_reports.sql, db/migrations/004_reference_biomarkers.sql, db/migrations/005_symptoms_goals_memory.sql, db/migrations/006_nutrition.sql, db/migrations/007_plans_grocery_alerts.sql, db/migrations/008_chat_audit.sql, db/migrations/009_domain_alignment.sql
-- Do not edit this file. Edit the source files and regenerate.
-- ==========================================================================


-- --------------------------------------------------------------------------
-- source: db/migrations/001_extensions.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 001_extensions.sql
-- HealthPulse - extensions and shared helpers
-- Target: PostgreSQL 15 (Supabase)
--
-- Run this FIRST. Safe to run more than once.
-- ============================================================================

-- pgcrypto gives us gen_random_uuid(). On Supabase it is normally already
-- installed in the "extensions" schema, in which case this line does nothing.
create extension if not exists pgcrypto;

-- pg_trgm powers fuzzy text search over food names and lab test names.
create extension if not exists pg_trgm;

-- ----------------------------------------------------------------------------
-- Shared trigger function: keeps updated_at honest.
-- Any table with an updated_at column gets a trigger that calls this.
-- ----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'BEFORE UPDATE trigger helper: stamps updated_at = now().';

-- --------------------------------------------------------------------------
-- source: db/migrations/002_identity.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 002_identity.sql
-- HealthPulse - identity, profile, allergies, consent
-- Target: PostgreSQL 15 (Supabase)
--
-- Depends on: 001_extensions.sql, and Supabase's built-in auth.users table.
-- Safe to run more than once.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Controlled vocabularies used across the whole schema.
-- These are written out as CHECK constraints rather than Postgres ENUM types so
-- that adding a value later is a one-line ALTER instead of a type migration.
--
--   sex (profile)      male | female | other | prefer_not_to_say
--   sex (reference)    male | female | any
--   activity_level     sedentary | moderate | heavy      (ICMR-NIN 2020 groups)
--   meal_slot          breakfast | mid_morning | lunch | snack | dinner | bedtime
--
-- The backend MUST use exactly these strings.
-- ----------------------------------------------------------------------------

-- ---------------------------------------------------------------- profiles --
create table if not exists public.profiles (
  user_id       uuid primary key references auth.users (id) on delete cascade,
  display_name  text,
  locale        text        not null default 'en-IN',
  timezone      text        not null default 'Asia/Kolkata',
  created_at    timestamptz not null default now()
);

comment on table public.profiles is
  'Non-medical account profile. One row per auth user.';

-- --------------------------------------------------------- health_profiles --
create table if not exists public.health_profiles (
  user_id        uuid primary key references auth.users (id) on delete cascade,
  dob            date,
  sex            text,
  height_cm      numeric(5,2) check (height_cm is null or (height_cm > 0 and height_cm < 300)),
  weight_kg      numeric(6,2) check (weight_kg is null or (weight_kg > 0 and weight_kg < 700)),
  activity_level text,
  diet_type      text,
  cuisine_pref   text[]      not null default '{}',
  city           text,
  pincode        text,
  wake_time      time,
  sleep_time     time,
  meal_times     jsonb       not null default '{}'::jsonb,
  conditions     text[]      not null default '{}',
  -- Not in the original sketch, added deliberately: reference_ranges is keyed by
  -- pregnancy status (see docs/04-ai-pipeline.md stage 4), so the profile has to
  -- be able to answer that question. Defaults to false; the user sets it.
  pregnancy      boolean     not null default false,
  updated_at     timestamptz not null default now(),
  constraint health_profiles_sex_check
    check (sex is null or sex in ('male', 'female', 'other', 'prefer_not_to_say')),
  constraint health_profiles_activity_level_check
    check (activity_level is null or activity_level in ('sedentary', 'moderate', 'heavy')),
  constraint health_profiles_diet_type_check
    check (diet_type is null or diet_type in ('veg', 'non_veg', 'egg', 'vegan', 'jain'))
);

comment on table public.health_profiles is
  'Clinical/dietary profile driving reference-range lookup and meal planning.';
comment on column public.health_profiles.pregnancy is
  'Pregnancy status. Used to pick the correct row from reference_ranges.';

drop trigger if exists trg_health_profiles_updated_at on public.health_profiles;
create trigger trg_health_profiles_updated_at
  before update on public.health_profiles
  for each row execute function public.set_updated_at();

-- --------------------------------------------------------------- allergies --
create table if not exists public.allergies (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  allergen   text not null,
  severity   text,
  created_at timestamptz not null default now(),
  constraint allergies_allergen_not_blank check (length(btrim(allergen)) > 0)
);

comment on table public.allergies is
  'User-declared food allergens. Hard filter on every candidate food list.';

create index if not exists idx_allergies_user_id
  on public.allergies (user_id);
create unique index if not exists uq_allergies_user_allergen
  on public.allergies (user_id, lower(btrim(allergen)));

-- ---------------------------------------------------------------- consents --
create table if not exists public.consents (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  consent_type text not null,
  version      text not null,
  accepted_at  timestamptz not null default now(),
  -- Hash only. We never store a raw IP address.
  ip_hash      text
);

comment on table public.consents is
  'Consent receipts. One row per (consent_type, version) the user accepted.';
comment on column public.consents.ip_hash is
  'Salted hash of the client IP. Never store the raw address.';

create index if not exists idx_consents_user_id
  on public.consents (user_id);
create unique index if not exists uq_consents_user_type_version
  on public.consents (user_id, consent_type, version);

-- --------------------------------------------------------------------------
-- source: db/migrations/003_reports.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 003_reports.sql
-- HealthPulse - uploaded reports, model extractions, structured lab results
-- Target: PostgreSQL 15 (Supabase)
--
-- Depends on: 002_identity.sql
-- Safe to run more than once.
--
-- NOTE: lab_results.biomarker_code gets its foreign key to biomarkers(code) in
-- 004_reference_biomarkers.sql, because the biomarkers table does not exist yet.
-- ============================================================================

-- ----------------------------------------------------------------- reports --
create table if not exists public.reports (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references auth.users (id) on delete cascade,
  storage_path        text not null,
  -- SHA-256 hex digest of the uploaded bytes. Same file uploaded twice costs no
  -- model call (docs/04-ai-pipeline.md stage 1).
  file_hash           text not null,
  mime_type           text,
  report_type         text,
  lab_name            text,
  collected_on        date,
  status              text not null default 'uploaded',
  -- Original file is deleted after this date unless the user opts to keep it.
  keep_original_until date not null default (current_date + 90),
  created_at          timestamptz not null default now(),
  constraint reports_status_check
    check (status in ('uploaded', 'extracting', 'extracted', 'failed')),
  constraint reports_file_hash_format
    check (file_hash ~ '^[0-9a-f]{64}$')
);

comment on table public.reports is
  'One row per uploaded lab report / scan / prescription file.';
comment on column public.reports.file_hash is
  'Lowercase SHA-256 hex of the file bytes. Unique per user for dedupe.';

-- Dedupe: the same user cannot store the same file twice.
create unique index if not exists uq_reports_user_file_hash
  on public.reports (user_id, file_hash);

create index if not exists idx_reports_user_id
  on public.reports (user_id);
create index if not exists idx_reports_user_collected_on
  on public.reports (user_id, collected_on desc);
create index if not exists idx_reports_status
  on public.reports (status) where status in ('uploaded', 'extracting');
-- Nightly job that deletes expired original files.
create index if not exists idx_reports_keep_original_until
  on public.reports (keep_original_until);

-- ------------------------------------------------------- report_extractions --
create table if not exists public.report_extractions (
  id         uuid primary key default gen_random_uuid(),
  report_id  uuid not null references public.reports (id) on delete cascade,
  model      text not null,
  raw_json   jsonb not null,
  tokens_in  integer check (tokens_in is null or tokens_in >= 0),
  tokens_out integer check (tokens_out is null or tokens_out >= 0),
  created_at timestamptz not null default now()
);

comment on table public.report_extractions is
  'Raw structured JSON returned by the extraction model, kept verbatim so a '
  're-parse never needs another model call. Ownership is inherited from reports.';

create index if not exists idx_report_extractions_report_id
  on public.report_extractions (report_id);

-- ------------------------------------------------------------- lab_results --
create table if not exists public.lab_results (
  id                uuid primary key default gen_random_uuid(),
  -- Nullable + ON DELETE SET NULL on purpose: report FILES expire after
  -- keep_original_until, but the structured values are the trend history and
  -- must survive (docs/03-data-model.md, "Retention").
  report_id         uuid references public.reports (id) on delete set null,
  user_id           uuid not null references auth.users (id) on delete cascade,
  biomarker_code    text,
  value             numeric,
  unit              text,
  -- Exactly what the lab printed, kept for the "show me the original" view.
  printed_range     text,
  ref_low           numeric,
  ref_high          numeric,
  status            text,
  -- True when the printed test name could not be mapped to a biomarker code
  -- confidently. We never silently guess a health value.
  needs_review      boolean not null default false,
  confirmed_by_user boolean not null default false,
  measured_on       date,
  created_at        timestamptz not null default now(),
  constraint lab_results_status_check
    check (status is null or status in (
      'critical_low', 'low', 'borderline_low', 'normal',
      'borderline_high', 'high', 'critical_high')),
  -- A row with no biomarker_code must be flagged for review, never used silently.
  constraint lab_results_unmapped_needs_review
    check (biomarker_code is not null or needs_review)
);

comment on table public.lab_results is
  'One structured lab value. status is set by the deterministic classifier '
  '(docs/04-ai-pipeline.md stage 4), never by the model.';
comment on column public.lab_results.needs_review is
  'true = we could not map name or unit confidently; must be confirmed by user.';

create index if not exists idx_lab_results_user_id
  on public.lab_results (user_id);
create index if not exists idx_lab_results_report_id
  on public.lab_results (report_id);
-- The trend query: "show my HbA1c over 2 years".
create index if not exists idx_lab_results_user_biomarker_measured_on
  on public.lab_results (user_id, biomarker_code, measured_on desc);
-- The review queue.
create index if not exists idx_lab_results_user_needs_review
  on public.lab_results (user_id) where needs_review;

-- --------------------------------------------------------------------------
-- source: db/migrations/004_reference_biomarkers.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 004_reference_biomarkers.sql
-- HealthPulse - shared reference tables for lab interpretation
-- Target: PostgreSQL 15 (Supabase)
--
-- Depends on: 003_reports.sql
-- Safe to run more than once.
--
-- These three tables are what stop "is this value abnormal?" from being a
-- question for the model (docs/04-ai-pipeline.md stages 3-5). They are shared,
-- read-only to logged-in users, and written only by the service role.
-- ============================================================================

-- -------------------------------------------------------------- biomarkers --
create table if not exists public.biomarkers (
  code            text primary key,
  display_name    text not null,
  category        text not null,
  -- Every lab_results.value is converted into this unit before comparison.
  canonical_unit  text not null,
  -- true  = a high value is the concerning direction (LDL, HbA1c)
  -- false = a low value is the concerning direction (Haemoglobin, Vitamin D)
  -- null  = both directions matter (Sodium, Potassium, Calcium)
  higher_is_worse boolean,
  created_at      timestamptz not null default now(),
  constraint biomarkers_code_format check (code ~ '^[A-Z0-9_]+$')
);

comment on table public.biomarkers is
  'Canonical biomarker catalogue. code is the join key used everywhere else.';

create index if not exists idx_biomarkers_category
  on public.biomarkers (category);

-- ------------------------------------------------------ biomarker_synonyms --
create table if not exists public.biomarker_synonyms (
  -- Store the LOWERCASED, whitespace-squashed printed test name. The backend
  -- must apply the same normalisation before looking a name up.
  synonym        text primary key,
  biomarker_code text not null references public.biomarkers (code) on delete cascade,
  source         text,
  created_at     timestamptz not null default now(),
  constraint biomarker_synonyms_lowercase check (synonym = lower(synonym)),
  constraint biomarker_synonyms_not_blank check (length(btrim(synonym)) > 0)
);

comment on table public.biomarker_synonyms is
  'Printed lab test name -> canonical biomarker code (pipeline stage 3). '
  'Keys are lowercase; the backend lowercases and squashes spaces before lookup.';

create index if not exists idx_biomarker_synonyms_biomarker_code
  on public.biomarker_synonyms (biomarker_code);
-- Fuzzy fallback for names that are close but not an exact synonym. A trigram
-- hit is a SUGGESTION only: the row is still stored with needs_review = true.
create index if not exists idx_biomarker_synonyms_trgm
  on public.biomarker_synonyms using gin (synonym gin_trgm_ops);

-- --------------------------------------------------------- reference_ranges --
create table if not exists public.reference_ranges (
  id              uuid primary key default gen_random_uuid(),
  biomarker_code  text not null references public.biomarkers (code) on delete cascade,
  -- 'any' means the range does not vary by sex.
  sex             text not null default 'any',
  -- Age band in whole years, inclusive of age_min, inclusive of age_max.
  age_min         integer not null default 0,
  age_max         integer not null default 120,
  -- null = row applies whatever the pregnancy status.
  -- true / false = row applies only to that status and wins over the null row.
  pregnancy       boolean,
  -- All thresholds are expressed in biomarkers.canonical_unit.
  low             numeric,
  high            numeric,
  borderline_low  numeric,
  borderline_high numeric,
  critical_low    numeric,
  critical_high   numeric,
  -- MANDATORY. We must always be able to say where a threshold came from.
  source_citation text not null,
  created_at      timestamptz not null default now(),
  constraint reference_ranges_sex_check
    check (sex in ('male', 'female', 'any')),
  constraint reference_ranges_age_band_check
    check (age_min >= 0 and age_max >= age_min and age_max <= 120),
  constraint reference_ranges_citation_not_blank
    check (length(btrim(source_citation)) > 0),
  -- A row that says nothing is a bug, not a range.
  constraint reference_ranges_has_a_threshold
    check (num_nonnulls(low, high, borderline_low, borderline_high,
                        critical_low, critical_high) > 0),
  -- Ordering sanity, checked only where both sides are present.
  constraint reference_ranges_low_below_high
    check (low is null or high is null or low <= high),
  constraint reference_ranges_critical_low_below_low
    check (critical_low is null or low is null or critical_low <= low),
  constraint reference_ranges_critical_high_above_high
    check (critical_high is null or high is null or critical_high >= high),
  -- borderline_* sit BETWEEN the frank cut-off and normal, so the six numbers
  -- must always read in this order, ignoring the nulls:
  --   critical_low <= low <= borderline_low <= borderline_high <= high <= critical_high
  constraint reference_ranges_borderline_low_above_low
    check (borderline_low is null or low is null or borderline_low >= low),
  constraint reference_ranges_borderline_high_below_high
    check (borderline_high is null or high is null or borderline_high <= high)
);

comment on table public.reference_ranges is
  'Deterministic classification table (pipeline stage 4). Every row must carry '
  'a source_citation. If a threshold is not confidently sourced, the row is '
  'omitted and the gap is recorded in db/seed/GAPS.md.';
comment on column public.reference_ranges.pregnancy is
  'null = applies to any pregnancy status. A true/false row overrides the null row.';

create index if not exists idx_reference_ranges_biomarker_code
  on public.reference_ranges (biomarker_code);
create index if not exists idx_reference_ranges_lookup
  on public.reference_ranges (biomarker_code, sex, age_min, age_max);

-- NULLS NOT DISTINCT (PostgreSQL 15+) so the "applies to any pregnancy status"
-- row cannot be inserted twice.
create unique index if not exists uq_reference_ranges_band
  on public.reference_ranges (biomarker_code, sex, age_min, age_max, pregnancy)
  nulls not distinct;

-- ------------------------------------------------- deferred FK from 003 -----
-- lab_results.biomarker_code -> biomarkers.code. Added here because biomarkers
-- did not exist when lab_results was created.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'lab_results_biomarker_code_fkey'
      and conrelid = 'public.lab_results'::regclass
  ) then
    alter table public.lab_results
      add constraint lab_results_biomarker_code_fkey
      foreign key (biomarker_code) references public.biomarkers (code)
      on delete restrict;
  end if;
end
$$;

-- Index for that foreign key. The (user_id, biomarker_code, measured_on) index
-- in 003 does not cover it, because biomarker_code is not its leading column -
-- so a "which results use this biomarker?" lookup, and the FK's own check when a
-- biomarker row is touched, would both have to scan the table without this.
create index if not exists idx_lab_results_biomarker_code
  on public.lab_results (biomarker_code);

-- --------------------------------------------------------------------------
-- source: db/migrations/005_symptoms_goals_memory.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 005_symptoms_goals_memory.sql
-- HealthPulse - symptoms, follow-up questions, goals, learned memory
-- Target: PostgreSQL 15 (Supabase)
--
-- Depends on: 004_reference_biomarkers.sql
-- Safe to run more than once.
--
-- NOTE: symptoms.source_message_id and user_memory.source_message_id get their
-- foreign keys to chat_messages(id) in 008_chat_audit.sql.
-- ============================================================================

-- ---------------------------------------------------------------- symptoms --
create table if not exists public.symptoms (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users (id) on delete cascade,
  label             text not null,
  onset             date,
  severity          text,
  pattern           text,
  -- The chat message this symptom was extracted from, so the user can always
  -- see why we think they have it.
  source_message_id uuid,
  status            text not null default 'active',
  created_at        timestamptz not null default now(),
  constraint symptoms_label_not_blank check (length(btrim(label)) > 0)
);

comment on table public.symptoms is
  'Symptoms extracted from chat or entered by the user. Red-flag classification '
  'is done by deterministic rules (pipeline stage 5), never by the model.';

create index if not exists idx_symptoms_user_id
  on public.symptoms (user_id);
create index if not exists idx_symptoms_user_status
  on public.symptoms (user_id, status);
create index if not exists idx_symptoms_source_message_id
  on public.symptoms (source_message_id);

-- ------------------------------------------------------- symptom_followups --
create table if not exists public.symptom_followups (
  id          uuid primary key default gen_random_uuid(),
  symptom_id  uuid not null references public.symptoms (id) on delete cascade,
  question    text not null,
  answer      text,
  asked_at    timestamptz not null default now(),
  answered_at timestamptz
);

comment on table public.symptom_followups is
  'Clarifying questions asked about a symptom. Ownership inherited from symptoms.';

create index if not exists idx_symptom_followups_symptom_id
  on public.symptom_followups (symptom_id);
create index if not exists idx_symptom_followups_unanswered
  on public.symptom_followups (symptom_id) where answered_at is null;

-- ------------------------------------------------------------------- goals --
create table if not exists public.goals (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  goal_type  text not null,
  title      text not null,
  target     text,
  priority   text,
  status     text not null default 'active',
  created_at timestamptz not null default now(),
  closed_at  timestamptz,
  constraint goals_goal_type_check
    check (goal_type in ('weight', 'hair', 'skin', 'energy',
                         'sleep', 'fitness', 'deficiency'))
);

comment on table public.goals is
  'User goals that steer plan generation (pipeline stage 6).';

create index if not exists idx_goals_user_id
  on public.goals (user_id);
create index if not exists idx_goals_user_status
  on public.goals (user_id, status);

-- ------------------------------------------------------------- user_memory --
create table if not exists public.user_memory (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users (id) on delete cascade,
  fact              text not null,
  category          text,
  -- 0.00 - 1.00. Low-confidence facts must be confirmed by the user before they
  -- are allowed to influence a plan.
  confidence        numeric(4,3) not null default 0.500,
  confirmed         boolean not null default false,
  source_message_id uuid,
  created_at        timestamptz not null default now(),
  expires_at        timestamptz,
  constraint user_memory_confidence_range
    check (confidence >= 0 and confidence <= 1),
  constraint user_memory_fact_not_blank check (length(btrim(fact)) > 0)
);

comment on table public.user_memory is
  'Atomic facts inferred from chat ("skips breakfast on workdays"). Inspectable '
  'and editable by the user; low-confidence rows are confirmed before use.';

create index if not exists idx_user_memory_user_id
  on public.user_memory (user_id);
-- The block the planner loads: live, usable facts for this user.
create index if not exists idx_user_memory_user_active
  on public.user_memory (user_id, category)
  where confirmed and expires_at is null;
create index if not exists idx_user_memory_expires_at
  on public.user_memory (expires_at) where expires_at is not null;
create index if not exists idx_user_memory_source_message_id
  on public.user_memory (source_message_id);

-- --------------------------------------------------------------------------
-- source: db/migrations/006_nutrition.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 006_nutrition.sql
-- HealthPulse - foods, recipes, RDA targets, preferences, food logs
-- Target: PostgreSQL 15 (Supabase)
--
-- Depends on: 005_symptoms_goals_memory.sql
-- Safe to run more than once.
--
-- foods, recipes, recipe_items and rda_targets are SHARED REFERENCE data.
-- Every nutrient number the user ever sees is computed from foods.per_100g by
-- the backend - never taken from model free text (CLAUDE.md, hard rules).
-- ============================================================================

-- ------------------------------------------------------------------- foods --
create table if not exists public.foods (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  -- Hindi / Telugu / Tamil / regional name as commonly written in English script.
  name_local  text,
  food_group  text not null,
  -- Nutrients per 100 g edible portion. Keys used by the backend:
  --   kcal, protein_g, fat_g, carb_g, fibre_g, iron_mg, calcium_mg,
  --   vitamin_d_ug, b12_ug, folate_ug, zinc_mg, magnesium_mg, potassium_mg,
  --   sodium_mg, vitamin_c_mg, vitamin_a_ug
  -- A key that is ABSENT means "we do not have a trustworthy value", which is
  -- different from a value of 0. The backend must treat missing as unknown.
  per_100g    jsonb not null default '{}'::jsonb,
  -- Subset of: veg, non_veg, egg, vegan, jain, gluten_free, high_protein,
  -- high_fibre, high_iron, high_calcium, low_gi
  diet_flags  text[] not null default '{}',
  -- Subset of: milk, egg, peanut, tree_nut, sesame, soy, fish, shellfish,
  -- gluten, mustard
  allergens   text[] not null default '{}',
  region      text,
  -- 'PROVISIONAL' marks a starter row whose numbers have NOT been checked
  -- against an authoritative table yet. See db/seed/GAPS.md.
  source      text not null,
  source_id   text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint foods_source_check
    check (source in ('IFCT2017', 'USDA', 'PROVISIONAL')),
  constraint foods_per_100g_is_object
    check (jsonb_typeof(per_100g) = 'object'),
  constraint foods_name_not_blank check (length(btrim(name)) > 0)
);

comment on table public.foods is
  'Food composition reference. The single source of truth for nutrient numbers.';
comment on column public.foods.source is
  'IFCT2017 / USDA = verified import. PROVISIONAL = starter value, not yet checked.';

create unique index if not exists uq_foods_source_source_id
  on public.foods (source, source_id);
create index if not exists idx_foods_food_group
  on public.foods (food_group);
create index if not exists idx_foods_diet_flags
  on public.foods using gin (diet_flags);
create index if not exists idx_foods_allergens
  on public.foods using gin (allergens);
create index if not exists idx_foods_per_100g
  on public.foods using gin (per_100g);
create index if not exists idx_foods_name_trgm
  on public.foods using gin (name gin_trgm_ops);

drop trigger if exists trg_foods_updated_at on public.foods;
create trigger trg_foods_updated_at
  before update on public.foods
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------- recipes --
create table if not exists public.recipes (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  cuisine      text,
  -- Subset of: breakfast, mid_morning, lunch, snack, dinner, bedtime
  meal_slots   text[] not null default '{}',
  prep_minutes integer check (prep_minutes is null or prep_minutes >= 0),
  diet_flags   text[] not null default '{}',
  -- JSON array of plain-text steps: ["Soak the rice 4 hours", "Grind ..."]
  steps        jsonb not null default '[]'::jsonb,
  source       text,
  source_id    text,
  created_at   timestamptz not null default now(),
  constraint recipes_steps_is_array check (jsonb_typeof(steps) = 'array'),
  constraint recipes_name_not_blank check (length(btrim(name)) > 0)
);

comment on table public.recipes is
  'Shared recipe reference. Nutrients are never stored here - they are computed '
  'from recipe_items joined to foods.';

create unique index if not exists uq_recipes_source_source_id
  on public.recipes (source, source_id) where source is not null and source_id is not null;
create index if not exists idx_recipes_meal_slots
  on public.recipes using gin (meal_slots);
create index if not exists idx_recipes_diet_flags
  on public.recipes using gin (diet_flags);
create index if not exists idx_recipes_name_trgm
  on public.recipes using gin (name gin_trgm_ops);

-- ------------------------------------------------------------ recipe_items --
create table if not exists public.recipe_items (
  recipe_id uuid not null references public.recipes (id) on delete cascade,
  food_id   uuid not null references public.foods (id)   on delete restrict,
  grams     numeric(8,2) not null check (grams > 0),
  primary key (recipe_id, food_id)
);

comment on table public.recipe_items is
  'Ingredient lines of a recipe. Reference data: visible when the parent recipe '
  'is visible, writable only by the service role.';

create index if not exists idx_recipe_items_recipe_id
  on public.recipe_items (recipe_id);
create index if not exists idx_recipe_items_food_id
  on public.recipe_items (food_id);

-- ------------------------------------------------------------- rda_targets --
create table if not exists public.rda_targets (
  id              uuid primary key default gen_random_uuid(),
  -- Matches a key in foods.per_100g where possible: energy_kcal, protein_g,
  -- calcium_mg, iron_mg, zinc_mg, vitamin_d_ug, b12_ug, folate_ug ...
  nutrient        text not null,
  sex             text not null default 'any',
  age_min         integer not null default 0,
  age_max         integer not null default 120,
  -- 'any' for nutrients whose target does not vary with activity.
  activity_level  text not null default 'any',
  amount          numeric not null check (amount >= 0),
  unit            text not null,
  source          text not null,
  -- Full reference so a dietitian can check any number against the printed table.
  source_citation text not null,
  created_at      timestamptz not null default now(),
  constraint rda_targets_sex_check
    check (sex in ('male', 'female', 'any')),
  constraint rda_targets_activity_level_check
    check (activity_level in ('sedentary', 'moderate', 'heavy', 'any')),
  constraint rda_targets_source_check
    check (source in ('ICMR-NIN 2020')),
  constraint rda_targets_age_band_check
    check (age_min >= 0 and age_max >= age_min and age_max <= 120),
  constraint rda_targets_citation_not_blank
    check (length(btrim(source_citation)) > 0)
);

comment on table public.rda_targets is
  'Daily nutrient targets. Drives the GAPS block handed to the planner.';

create unique index if not exists uq_rda_targets_band
  on public.rda_targets (nutrient, sex, age_min, age_max, activity_level);
create index if not exists idx_rda_targets_lookup
  on public.rda_targets (sex, activity_level, nutrient);

-- ------------------------------------------------------- food_preferences --
create table if not exists public.food_preferences (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  food_id    uuid not null references public.foods (id) on delete cascade,
  stance     text not null default 'neutral',
  -- Rolling score from ratings, frequency, skips and recency. Pure arithmetic.
  score      numeric(5,2) not null default 0,
  updated_at timestamptz not null default now(),
  constraint food_preferences_stance_check
    check (stance in ('like', 'dislike', 'neutral', 'never'))
);

comment on table public.food_preferences is
  'Declared + observed preference per food. "never" is a hard exclusion.';

create unique index if not exists uq_food_preferences_user_food
  on public.food_preferences (user_id, food_id);
create index if not exists idx_food_preferences_user_id
  on public.food_preferences (user_id);
create index if not exists idx_food_preferences_food_id
  on public.food_preferences (food_id);

drop trigger if exists trg_food_preferences_updated_at on public.food_preferences;
create trigger trg_food_preferences_updated_at
  before update on public.food_preferences
  for each row execute function public.set_updated_at();

-- --------------------------------------------------------------- food_logs --
create table if not exists public.food_logs (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  logged_at  timestamptz not null default now(),
  meal_slot  text,
  -- Nullable: a free-text or photo log may not resolve to a catalogue food.
  food_id    uuid references public.foods (id) on delete set null,
  free_text  text,
  image_path text,
  source     text not null default 'manual',
  created_at timestamptz not null default now(),
  constraint food_logs_source_check
    check (source in ('planned', 'chat', 'photo', 'manual')),
  constraint food_logs_meal_slot_check
    check (meal_slot is null or meal_slot in
      ('breakfast', 'mid_morning', 'lunch', 'snack', 'dinner', 'bedtime')),
  -- A log with nothing in it is not a log.
  constraint food_logs_has_content
    check (food_id is not null or length(btrim(coalesce(free_text, ''))) > 0
           or image_path is not null)
);

comment on table public.food_logs is
  'What the user actually ate. Feeds the observed-preference score.';

create index if not exists idx_food_logs_user_id
  on public.food_logs (user_id);
create index if not exists idx_food_logs_food_id
  on public.food_logs (food_id);
-- The diary query: "what did I eat this week".
create index if not exists idx_food_logs_user_logged_at
  on public.food_logs (user_id, logged_at desc);

-- ---------------------------------------------------------- food_feedback --
create table if not exists public.food_feedback (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,
  food_log_id uuid not null references public.food_logs (id) on delete cascade,
  rating      smallint not null,
  note        text,
  created_at  timestamptz not null default now(),
  constraint food_feedback_rating_range check (rating between 1 and 5)
);

comment on table public.food_feedback is
  'Star rating on a logged meal. Drives "Dropped soya chunks - you rated it 1 star twice".';

create unique index if not exists uq_food_feedback_food_log
  on public.food_feedback (food_log_id);
create index if not exists idx_food_feedback_user_id
  on public.food_feedback (user_id);
create index if not exists idx_food_feedback_food_log_id
  on public.food_feedback (food_log_id);

-- --------------------------------------------------------------------------
-- source: db/migrations/007_plans_grocery_alerts.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 007_plans_grocery_alerts.sql
-- HealthPulse - meal plans, grocery lists, pantry, alerts
-- Target: PostgreSQL 15 (Supabase)
--
-- Depends on: 006_nutrition.sql
-- Safe to run more than once.
-- ============================================================================

-- -------------------------------------------------------------- meal_plans --
create table if not exists public.meal_plans (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  plan_date    date not null,
  generated_at timestamptz not null default now(),
  model        text,
  -- Plain-English "why this plan looks like this" shown to the user.
  rationale    text,
  status       text not null default 'draft',
  constraint meal_plans_status_check
    check (status in ('draft', 'active', 'superseded', 'failed'))
);

comment on table public.meal_plans is
  'One plan per user per day. Screens read stored plans; we generate once a day.';

-- One plan per user per day keeps us inside the free tier.
create unique index if not exists uq_meal_plans_user_plan_date
  on public.meal_plans (user_id, plan_date);
create index if not exists idx_meal_plans_user_id
  on public.meal_plans (user_id);
create index if not exists idx_meal_plans_user_plan_date
  on public.meal_plans (user_id, plan_date desc);

-- --------------------------------------------------------- meal_plan_items --
create table if not exists public.meal_plan_items (
  id                 uuid primary key default gen_random_uuid(),
  meal_plan_id       uuid not null references public.meal_plans (id) on delete cascade,
  meal_slot          text not null,
  recipe_id          uuid references public.recipes (id) on delete set null,
  food_id            uuid references public.foods (id)   on delete set null,
  grams              numeric(8,2) check (grams is null or grams > 0),
  -- Recomputed in Python from the foods table (pipeline stage 7). Whatever the
  -- model claimed is discarded before this is written.
  computed_nutrients jsonb not null default '{}'::jsonb,
  why_text           text,
  order_index        integer not null default 0,
  created_at         timestamptz not null default now(),
  constraint meal_plan_items_meal_slot_check
    check (meal_slot in ('breakfast', 'mid_morning', 'lunch',
                         'snack', 'dinner', 'bedtime')),
  constraint meal_plan_items_needs_a_thing
    check (recipe_id is not null or food_id is not null),
  constraint meal_plan_items_nutrients_is_object
    check (jsonb_typeof(computed_nutrients) = 'object')
);

comment on table public.meal_plan_items is
  'One dish/food in a plan. computed_nutrients is always recomputed server-side.';

create index if not exists idx_meal_plan_items_meal_plan_id
  on public.meal_plan_items (meal_plan_id);
create index if not exists idx_meal_plan_items_recipe_id
  on public.meal_plan_items (recipe_id);
create index if not exists idx_meal_plan_items_food_id
  on public.meal_plan_items (food_id);
create index if not exists idx_meal_plan_items_plan_order
  on public.meal_plan_items (meal_plan_id, meal_slot, order_index);

-- ----------------------------------------------------------- grocery_lists --
create table if not exists public.grocery_lists (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  week_start date not null,
  status     text not null default 'open',
  created_at timestamptz not null default now(),
  constraint grocery_lists_status_check
    check (status in ('open', 'shopping', 'done', 'archived'))
);

comment on table public.grocery_lists is 'One shopping list per user per week.';

create unique index if not exists uq_grocery_lists_user_week
  on public.grocery_lists (user_id, week_start);
create index if not exists idx_grocery_lists_user_id
  on public.grocery_lists (user_id);
create index if not exists idx_grocery_lists_user_week_start
  on public.grocery_lists (user_id, week_start desc);

-- ----------------------------------------------------------- grocery_items --
create table if not exists public.grocery_items (
  id              uuid primary key default gen_random_uuid(),
  grocery_list_id uuid not null references public.grocery_lists (id) on delete cascade,
  food_id         uuid not null references public.foods (id) on delete restrict,
  quantity        numeric(10,2) not null check (quantity > 0),
  unit            text not null default 'g',
  -- Shop aisle grouping so the list is walkable: "Vegetables", "Dals", "Dairy".
  aisle           text,
  state           text not null default 'need',
  created_at      timestamptz not null default now(),
  constraint grocery_items_state_check
    check (state in ('need', 'have', 'bought'))
);

comment on table public.grocery_items is
  'A line on a shopping list. Ownership inherited from grocery_lists.';

create unique index if not exists uq_grocery_items_list_food
  on public.grocery_items (grocery_list_id, food_id);
create index if not exists idx_grocery_items_grocery_list_id
  on public.grocery_items (grocery_list_id);
create index if not exists idx_grocery_items_food_id
  on public.grocery_items (food_id);

-- ------------------------------------------------------------ pantry_items --
create table if not exists public.pantry_items (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  food_id    uuid not null references public.foods (id) on delete cascade,
  quantity   numeric(10,2) not null default 0 check (quantity >= 0),
  unit       text not null default 'g',
  updated_at timestamptz not null default now()
);

comment on table public.pantry_items is
  'What the user already has at home, so the grocery list does not re-buy it.';

create unique index if not exists uq_pantry_items_user_food
  on public.pantry_items (user_id, food_id);
create index if not exists idx_pantry_items_user_id
  on public.pantry_items (user_id);
create index if not exists idx_pantry_items_food_id
  on public.pantry_items (food_id);

drop trigger if exists trg_pantry_items_updated_at on public.pantry_items;
create trigger trg_pantry_items_updated_at
  before update on public.pantry_items
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------ alerts --
create table if not exists public.alerts (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users (id) on delete cascade,
  alert_type    text not null,
  title         text not null,
  body          text,
  -- Human-readable schedule the phone turns into local alarms, e.g.
  -- 'RRULE:FREQ=DAILY;BYHOUR=8,11,14,17,20' or 'daily 07:30'.
  schedule_rule text,
  enabled       boolean not null default true,
  -- {"start": "22:00", "end": "07:00"} - never fire inside this window.
  quiet_hours   jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  constraint alerts_alert_type_check
    check (alert_type in ('hydration', 'meal', 'grocery', 'activity', 'sleep',
                          'nutrition', 'report_followup', 'weekly_summary',
                          'escalation')),
  constraint alerts_quiet_hours_is_object
    check (jsonb_typeof(quiet_hours) = 'object')
);

comment on table public.alerts is
  'Alert definitions. The phone schedules these locally (AlarmManager), so they '
  'fire with the app closed and with no internet.';

create index if not exists idx_alerts_user_id
  on public.alerts (user_id);
create index if not exists idx_alerts_user_enabled
  on public.alerts (user_id, alert_type) where enabled;

-- -------------------------------------------------------- alert_deliveries --
create table if not exists public.alert_deliveries (
  id          uuid primary key default gen_random_uuid(),
  alert_id    uuid not null references public.alerts (id) on delete cascade,
  user_id     uuid not null references auth.users (id) on delete cascade,
  fired_at    timestamptz not null default now(),
  opened_at   timestamptz,
  actioned_at timestamptz,
  action      text
);

comment on table public.alert_deliveries is
  'Did the nudge fire, did they open it, did they act. Feeds the weekly summary.';

create index if not exists idx_alert_deliveries_alert_id
  on public.alert_deliveries (alert_id);
create index if not exists idx_alert_deliveries_user_id
  on public.alert_deliveries (user_id);
create index if not exists idx_alert_deliveries_user_fired_at
  on public.alert_deliveries (user_id, fired_at desc);

-- --------------------------------------------------------------------------
-- source: db/migrations/008_chat_audit.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 008_chat_audit.sql
-- HealthPulse - chat, audit trail, AI run ledger, deletion receipts
-- Target: PostgreSQL 15 (Supabase)
--
-- Depends on: 007_plans_grocery_alerts.sql
-- Safe to run more than once.
-- ============================================================================

-- ------------------------------------------------------------ chat_threads --
create table if not exists public.chat_threads (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  title      text,
  created_at timestamptz not null default now()
);

comment on table public.chat_threads is 'A conversation. One user, many threads.';

create index if not exists idx_chat_threads_user_id
  on public.chat_threads (user_id);
create index if not exists idx_chat_threads_user_created_at
  on public.chat_threads (user_id, created_at desc);

-- ----------------------------------------------------------- chat_messages --
create table if not exists public.chat_messages (
  id          uuid primary key default gen_random_uuid(),
  thread_id   uuid not null references public.chat_threads (id) on delete cascade,
  user_id     uuid not null references auth.users (id) on delete cascade,
  role        text not null,
  content     text not null default '',
  -- [{"type": "report", "report_id": "..."}, {"type": "image", "path": "..."}]
  attachments jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now(),
  constraint chat_messages_role_check
    check (role in ('user', 'assistant', 'system')),
  constraint chat_messages_attachments_is_array
    check (jsonb_typeof(attachments) = 'array')
);

comment on table public.chat_messages is
  'Chat turns. Kept until the user asks for deletion (docs/03-data-model.md).';

create index if not exists idx_chat_messages_user_id
  on public.chat_messages (user_id);
create index if not exists idx_chat_messages_thread_id
  on public.chat_messages (thread_id);
-- The screen query: load a thread oldest-first.
create index if not exists idx_chat_messages_thread_created_at
  on public.chat_messages (thread_id, created_at);

-- ------------------------------------------------- deferred FKs from 005 ----
-- symptoms.source_message_id and user_memory.source_message_id point at the
-- chat message they were extracted from. ON DELETE SET NULL: deleting a message
-- must not delete the symptom or the learned fact.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'symptoms_source_message_id_fkey'
      and conrelid = 'public.symptoms'::regclass
  ) then
    alter table public.symptoms
      add constraint symptoms_source_message_id_fkey
      foreign key (source_message_id) references public.chat_messages (id)
      on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'user_memory_source_message_id_fkey'
      and conrelid = 'public.user_memory'::regclass
  ) then
    alter table public.user_memory
      add constraint user_memory_source_message_id_fkey
      foreign key (source_message_id) references public.chat_messages (id)
      on delete set null;
  end if;
end
$$;

-- ----------------------------------------------------------- health_events --
create table if not exists public.health_events (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,
  event_type  text not null,
  payload     jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint health_events_payload_is_object
    check (jsonb_typeof(payload) = 'object')
);

comment on table public.health_events is
  'APPEND-ONLY audit trail. Users may read and insert; there is deliberately no '
  'UPDATE or DELETE policy, so an audit row cannot be rewritten from the app. '
  'Account deletion is done by the service role, which bypasses RLS.';

create index if not exists idx_health_events_user_id
  on public.health_events (user_id);
create index if not exists idx_health_events_user_occurred_at
  on public.health_events (user_id, occurred_at desc);
create index if not exists idx_health_events_type
  on public.health_events (event_type, occurred_at desc);

-- ---------------------------------------------------------------- ai_runs --
create table if not exists public.ai_runs (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users (id) on delete cascade,
  task           text not null,
  model          text not null,
  -- HASH ONLY. Prompt contents are never stored (docs/03-data-model.md).
  prompt_hash    text,
  tokens_in      integer check (tokens_in is null or tokens_in >= 0),
  tokens_out     integer check (tokens_out is null or tokens_out >= 0),
  latency_ms     integer check (latency_ms is null or latency_ms >= 0),
  safety_verdict text,
  regenerated    boolean not null default false,
  created_at     timestamptz not null default now(),
  constraint ai_runs_prompt_hash_format
    check (prompt_hash is null or prompt_hash ~ '^[0-9a-f]{64}$')
);

comment on table public.ai_runs is
  'APPEND-ONLY cost and safety ledger for every model call. Prompt hashes only, '
  'never prompt contents. Retention 180 days.';
comment on column public.ai_runs.prompt_hash is
  'SHA-256 hex of the prompt. Used to spot repeats; cannot be reversed.';

create index if not exists idx_ai_runs_user_id
  on public.ai_runs (user_id);
create index if not exists idx_ai_runs_user_created_at
  on public.ai_runs (user_id, created_at desc);
create index if not exists idx_ai_runs_created_at
  on public.ai_runs (created_at);
create index if not exists idx_ai_runs_safety_verdict
  on public.ai_runs (safety_verdict, created_at desc);

-- ------------------------------------------------------- weekly_summaries --
create table if not exists public.weekly_summaries (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  week_start date not null,
  metrics    jsonb not null default '{}'::jsonb,
  narrative  text,
  model      text,
  created_at timestamptz not null default now(),
  constraint weekly_summaries_metrics_is_object
    check (jsonb_typeof(metrics) = 'object')
);

comment on table public.weekly_summaries is
  'One batched Gemini 2.5 Pro review per user per week.';

create unique index if not exists uq_weekly_summaries_user_week
  on public.weekly_summaries (user_id, week_start);
create index if not exists idx_weekly_summaries_user_id
  on public.weekly_summaries (user_id);
create index if not exists idx_weekly_summaries_user_week_start
  on public.weekly_summaries (user_id, week_start desc);

-- ------------------------------------------------------ deletion_requests --
create table if not exists public.deletion_requests (
  id              uuid primary key default gen_random_uuid(),
  -- ON DELETE SET NULL, not CASCADE: the receipt has to outlive the account it
  -- describes, otherwise "we deleted your data" has no evidence.
  user_id         uuid references auth.users (id) on delete set null,
  requested_at    timestamptz not null default now(),
  completed_at    timestamptz,
  objects_deleted integer check (objects_deleted is null or objects_deleted >= 0),
  rows_deleted    integer check (rows_deleted is null or rows_deleted >= 0)
);

comment on table public.deletion_requests is
  'Receipt for "delete all my health data". Survives the account it refers to.';

create index if not exists idx_deletion_requests_user_id
  on public.deletion_requests (user_id);
create index if not exists idx_deletion_requests_open
  on public.deletion_requests (requested_at) where completed_at is null;

-- --------------------------------------------------------------------------
-- source: db/migrations/009_domain_alignment.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 009_domain_alignment.sql
--
-- Closes the gaps between backend/app/domain/enums.py and the schema, found
-- while wiring the API layer. Written as a separate migration rather than an
-- edit to 002/003/007 because "create table if not exists" does not alter a
-- table that already exists -- so editing an earlier file would silently do
-- nothing for anyone who has already run it.
--
-- Safe to run more than once.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. activity_level accepted only 3 of the 5 values ActivityLevel defines.
--
-- This was a real, user-visible defect: the repository had to fold `light` into
-- `sedentary` and `very_active` into `active`, so someone who set "very active"
-- during onboarding and reopened the app was shown "active". The nutrition
-- targets also key off activity, so the stored value silently changed what the
-- app recommended.
--
-- The RDA seed in 203_rda_targets.sql is keyed on the 3 ICMR-NIN bands, so
-- targets.py continues to map the 5 profile values onto those 3 bands. That
-- mapping is arithmetic, applied at lookup, and loses nothing stored.
-- ---------------------------------------------------------------------------
alter table public.health_profiles
  drop constraint if exists health_profiles_activity_level_check;

alter table public.health_profiles
  add constraint health_profiles_activity_level_check
  check (activity_level is null or activity_level in
         ('sedentary', 'light', 'moderate', 'active', 'very_active'));

-- ---------------------------------------------------------------------------
-- 2. meal_slot used 'snack'/'bedtime'; MealSlot defines 'evening_snack'.
-- Accept both spellings so existing rows stay valid, and let the enum's value
-- through. 'bedtime' has no enum member and is kept only so no row is orphaned.
-- ---------------------------------------------------------------------------
alter table public.meal_plan_items
  drop constraint if exists meal_plan_items_meal_slot_check;

alter table public.meal_plan_items
  add constraint meal_plan_items_meal_slot_check
  check (meal_slot in ('breakfast', 'mid_morning', 'lunch',
                       'evening_snack', 'snack', 'dinner', 'bedtime'));

-- ---------------------------------------------------------------------------
-- 3. A lab row that maps to no known biomarker had nowhere to record what the
-- report actually printed, or why it needs review. Without these the review
-- queue had to be rebuilt by re-running the normaliser over the stored raw
-- extraction every time. The whole point of needs_review is that a human
-- confirms an unrecognised value, and they cannot confirm what we did not keep.
-- ---------------------------------------------------------------------------
alter table public.lab_results
  add column if not exists printed_test_name text;

alter table public.lab_results
  add column if not exists review_reason text;

-- ---------------------------------------------------------------------------
-- 4. The daily hydration target belongs on the plan, not buried in a
-- health_events payload that has to be parsed back out.
-- ---------------------------------------------------------------------------
alter table public.meal_plans
  add column if not exists hydration_ml integer;

-- ---------------------------------------------------------------------------
-- 5. Sex 'prefer_not_to_say' is accepted by the schema but has no enum member,
-- so it reads back as Sex.OTHER. Left as is deliberately: the two mean
-- different things to a person, and collapsing them at write time would be the
-- same defect as (1). Recorded here so the next person sees it was a choice.
-- Adding a PREFER_NOT_TO_SAY member to Sex is the real fix, and it changes
-- reference-range selection, so it wants a deliberate pass.
-- ---------------------------------------------------------------------------

-- Check: all four alterations should report true.
select
  (select count(*) = 5 from unnest(array['sedentary','light','moderate','active','very_active']) v
     where pg_get_constraintdef(c.oid) like '%' || v || '%') as activity_ok,
  (select pg_get_constraintdef(c2.oid) like '%evening_snack%') as meal_slot_ok,
  (select count(*) = 2 from information_schema.columns
     where table_name = 'lab_results' and column_name in ('printed_test_name','review_reason')) as lab_cols_ok,
  (select count(*) = 1 from information_schema.columns
     where table_name = 'meal_plans' and column_name = 'hydration_ml') as hydration_ok
from pg_constraint c, pg_constraint c2
where c.conname = 'health_profiles_activity_level_check'
  and c2.conname = 'meal_plan_items_meal_slot_check';
