-- ==========================================================================
-- Part 3 of 3 - the reference data
--
-- Loads the biomarkers, the lab-name synonyms, the cited reference ranges, the nutrient targets and the food table.
-- Run this last.
--
-- HOW TO RUN THIS
--   1. Open your Supabase project.
--   2. Click the SQL Editor icon in the far-left sidebar.
--   3. Click 'New query'.
--   4. Paste this whole file in.
--   5. Click 'Run' (or press Ctrl+Enter).
--
-- It is safe to run more than once. If you are not sure whether it worked,
-- just run it again -- nothing is duplicated and nothing is lost.
--
-- Generated from: db/seed/200_biomarkers.sql, db/seed/201_biomarker_synonyms.sql, db/seed/202_reference_ranges.sql, db/seed/203_rda_targets.sql, db/seed/204_foods_starter.sql
-- Do not edit this file. Edit the source files and regenerate.
-- ==========================================================================


-- --------------------------------------------------------------------------
-- source: db/seed/200_biomarkers.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 200_biomarkers.sql
-- HealthPulse seed - canonical biomarker catalogue
--
-- Run AFTER the migrations and the policy files.
-- Safe to run more than once (ON CONFLICT DO NOTHING).
--
-- 82 biomarkers covering the panels an Indian lab normally prints:
-- CBC, lipid, thyroid, liver (LFT), kidney (KFT/RFT), glycaemic (fasting / PP /
-- HbA1c), vitamins (D, B12, folate, A), iron studies (ferritin, iron, TIBC,
-- transferrin saturation), minerals and electrolytes, and a short tail of
-- commonly ordered extras.
--
-- canonical_unit is the unit EVERY lab_results.value must be converted into
-- before it is compared with reference_ranges. Units are written in plain ASCII
-- (ug, uIU, umol) so nothing breaks when this file is pasted into a browser.
--
-- higher_is_worse:  true  = a high value is the concerning direction
--                   false = a low value is the concerning direction
--                   null  = both directions matter
-- ============================================================================

insert into public.biomarkers (code, display_name, category, canonical_unit, higher_is_worse)
values
  -- haematology
  ('HB', 'Haemoglobin', 'haematology', 'g/dL', false),
  ('RBC', 'Red Blood Cell Count', 'haematology', 'million/uL', null),
  ('WBC', 'Total Leucocyte Count (WBC)', 'haematology', '10^3/uL', null),
  ('PLT', 'Platelet Count', 'haematology', '10^3/uL', false),
  ('PCV', 'Packed Cell Volume (Haematocrit)', 'haematology', '%', null),
  ('MCV', 'Mean Corpuscular Volume', 'haematology', 'fL', null),
  ('MCH', 'Mean Corpuscular Haemoglobin', 'haematology', 'pg', null),
  ('MCHC', 'Mean Corpuscular Haemoglobin Concentration', 'haematology', 'g/dL', null),
  ('RDW', 'Red Cell Distribution Width', 'haematology', '%', true),
  -- Printed on the Redcliffe/AHC hybrid panel used in Hyderabad.
  ('PDW', 'Platelet Distribution Width', 'haematology', 'fL', null),
  ('MPV', 'Mean Platelet Volume', 'haematology', 'fL', null),
  ('NEUT_PCT', 'Neutrophils', 'haematology', '%', null),
  -- Absolute neutrophil count, not the percentage. The neutropenia red-flag rule
  -- in backend/app/rules/red_flags.py fires below 500 cells/uL and can only ever
  -- fire on an absolute count, so this code must exist for that rule to be live.
  ('NEUTROPHILS_ABS', 'Absolute Neutrophil Count', 'haematology', 'cells/uL', false),
  ('LYMPH_PCT', 'Lymphocytes', 'haematology', '%', null),
  ('MONO_PCT', 'Monocytes', 'haematology', '%', null),
  ('EOS_PCT', 'Eosinophils', 'haematology', '%', true),
  ('BASO_PCT', 'Basophils', 'haematology', '%', null),
  ('ESR', 'Erythrocyte Sedimentation Rate', 'haematology', 'mm/hr', true),
  ('RETIC_PCT', 'Reticulocyte Count', 'haematology', '%', null),
  -- lipid
  ('CHOL_TOTAL', 'Total Cholesterol', 'lipid', 'mg/dL', true),
  ('HDL', 'HDL Cholesterol', 'lipid', 'mg/dL', false),
  ('LDL', 'LDL Cholesterol', 'lipid', 'mg/dL', true),
  ('VLDL', 'VLDL Cholesterol', 'lipid', 'mg/dL', true),
  ('TRIG', 'Triglycerides', 'lipid', 'mg/dL', true),
  ('NON_HDL', 'Non-HDL Cholesterol', 'lipid', 'mg/dL', true),
  ('CHOL_HDL_RATIO', 'Total Cholesterol / HDL Ratio', 'lipid', 'ratio', true),
  ('LDL_HDL_RATIO', 'LDL / HDL Ratio', 'lipid', 'ratio', true),
  ('TRIG_HDL_RATIO', 'Triglyceride / HDL Ratio', 'lipid', 'ratio', true),
  ('LIPOPROTEIN_A', 'Lipoprotein (a)', 'lipid', 'mg/dL', true),
  ('APO_B', 'Apolipoprotein B', 'lipid', 'mg/dL', true),
  -- thyroid
  ('TSH', 'Thyroid Stimulating Hormone', 'thyroid', 'uIU/mL', null),
  ('FT3', 'Free T3', 'thyroid', 'pg/mL', null),
  ('FT4', 'Free T4', 'thyroid', 'ng/dL', null),
  ('T3_TOTAL', 'Total T3', 'thyroid', 'ng/dL', null),
  ('T4_TOTAL', 'Total T4', 'thyroid', 'ug/dL', null),
  ('ANTI_TPO', 'Anti-Thyroid Peroxidase Antibody', 'thyroid', 'IU/mL', true),
  -- liver
  ('BILI_TOTAL', 'Total Bilirubin', 'liver', 'mg/dL', true),
  ('BILI_DIRECT', 'Direct Bilirubin', 'liver', 'mg/dL', true),
  ('BILI_INDIRECT', 'Indirect Bilirubin', 'liver', 'mg/dL', true),
  ('ALT', 'SGPT (ALT)', 'liver', 'U/L', true),
  ('AST', 'SGOT (AST)', 'liver', 'U/L', true),
  ('ALP', 'Alkaline Phosphatase', 'liver', 'U/L', true),
  ('GGT', 'Gamma GT', 'liver', 'U/L', true),
  ('PROTEIN_TOTAL', 'Total Protein', 'liver', 'g/dL', null),
  ('ALBUMIN', 'Albumin', 'liver', 'g/dL', false),
  ('GLOBULIN', 'Globulin', 'liver', 'g/dL', null),
  ('AG_RATIO', 'Albumin / Globulin Ratio', 'liver', 'ratio', false),
  -- kidney
  ('UREA', 'Blood Urea', 'kidney', 'mg/dL', true),
  ('BUN', 'Blood Urea Nitrogen', 'kidney', 'mg/dL', true),
  ('CREATININE', 'Serum Creatinine', 'kidney', 'mg/dL', true),
  ('EGFR', 'Estimated GFR', 'kidney', 'mL/min/1.73m2', false),
  ('URIC_ACID', 'Uric Acid', 'kidney', 'mg/dL', true),
  ('UACR', 'Urine Albumin / Creatinine Ratio', 'kidney', 'mg/g', true),
  -- glycaemic
  ('GLUCOSE_FASTING', 'Fasting Blood Glucose', 'glycaemic', 'mg/dL', true),
  ('GLUCOSE_PP', 'Post Prandial Blood Glucose (2 hr)', 'glycaemic', 'mg/dL', true),
  ('GLUCOSE_RANDOM', 'Random Blood Glucose', 'glycaemic', 'mg/dL', true),
  ('HBA1C', 'Glycated Haemoglobin (HbA1c)', 'glycaemic', '%', true),
  ('INSULIN_FASTING', 'Fasting Insulin', 'glycaemic', 'uIU/mL', true),
  -- vitamin
  ('VITD_25OH', 'Vitamin D (25-OH)', 'vitamin', 'ng/mL', false),
  ('VITB12', 'Vitamin B12 (Cobalamin)', 'vitamin', 'pg/mL', false),
  ('FOLATE', 'Folate (Folic Acid)', 'vitamin', 'ng/mL', false),
  ('VITA', 'Vitamin A (Retinol)', 'vitamin', 'ug/dL', false),
  -- iron_studies
  ('FERRITIN', 'Ferritin', 'iron_studies', 'ng/mL', false),
  ('IRON', 'Serum Iron', 'iron_studies', 'ug/dL', false),
  ('TIBC', 'Total Iron Binding Capacity', 'iron_studies', 'ug/dL', null),
  ('UIBC', 'Unsaturated Iron Binding Capacity', 'iron_studies', 'ug/dL', null),
  ('TRANSFERRIN_SAT', 'Transferrin Saturation', 'iron_studies', '%', false),
  -- mineral
  ('CALCIUM', 'Serum Calcium (Total)', 'mineral', 'mg/dL', null),
  ('CALCIUM_IONIZED', 'Ionised Calcium', 'mineral', 'mg/dL', null),
  ('PHOSPHORUS', 'Serum Phosphorus', 'mineral', 'mg/dL', null),
  ('MAGNESIUM', 'Serum Magnesium', 'mineral', 'mg/dL', null),
  -- Referenced by the biomarker-to-nutrient map in backend/app/nutrition/gaps.py.
  ('ZINC', 'Serum Zinc', 'mineral', 'ug/dL', false),
  -- electrolyte
  ('SODIUM', 'Serum Sodium', 'electrolyte', 'mmol/L', null),
  ('POTASSIUM', 'Serum Potassium', 'electrolyte', 'mmol/L', null),
  ('CHLORIDE', 'Serum Chloride', 'electrolyte', 'mmol/L', null),
  ('BICARBONATE', 'Serum Bicarbonate', 'electrolyte', 'mmol/L', null),
  -- inflammation
  ('CRP_HS', 'High Sensitivity C-Reactive Protein', 'inflammation', 'mg/L', true),
  -- metabolic
  ('HOMOCYSTEINE', 'Homocysteine', 'metabolic', 'umol/L', true),
  -- Derived from HbA1c by the lab, not measured. Classified as UNKNOWN unless a
  -- cited range is ever added; it is shown for continuity with the printed report.
  ('AVG_GLUCOSE', 'Average Blood Glucose (from HbA1c)', 'metabolic', 'mg/dL', true),
  -- tumour_marker
  ('PSA', 'Prostate Specific Antigen (Total)', 'tumour_marker', 'ng/mL', true),
  -- muscle
  ('CPK', 'Creatine Phosphokinase', 'muscle', 'U/L', true),
  -- pancreas
  ('AMYLASE', 'Serum Amylase', 'pancreas', 'U/L', true),
  ('LIPASE', 'Serum Lipase', 'pancreas', 'U/L', true),
  -- metabolic
  ('LDH', 'Lactate Dehydrogenase', 'metabolic', 'U/L', true),
  -- hormone
  ('CORTISOL_AM', 'Serum Cortisol (Morning)', 'hormone', 'ug/dL', null),
  ('PTH', 'Parathyroid Hormone', 'hormone', 'pg/mL', null),
  ('TESTOSTERONE_TOTAL', 'Total Testosterone', 'hormone', 'ng/dL', null),
  ('PROLACTIN', 'Prolactin', 'hormone', 'ng/mL', true)
on conflict (code) do nothing;

-- Check: this must print 88.
select count(*) as biomarkers_loaded from public.biomarkers;

-- --------------------------------------------------------------------------
-- source: db/seed/201_biomarker_synonyms.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 201_biomarker_synonyms.sql
-- HealthPulse seed - printed lab test name -> canonical biomarker code
--
-- Run AFTER 200_biomarkers.sql. Safe to run more than once.
--
-- 353 synonyms. These are the names as they appear on Indian lab reports
-- (Thyrocare / Dr Lal PathLabs / Apollo / Metropolis style naming), including
-- the British and American spellings, the "S." and "Serum" prefixes, the
-- bracketed abbreviations and the hyphenated variants that all mean the same
-- test.
--
-- IMPORTANT - how the lookup works (docs/04-ai-pipeline.md stage 3):
--   The backend must LOWERCASE the printed name and squash runs of whitespace
--   to a single space before looking it up here. Every key below is already in
--   that form. An exact hit maps the row. A miss is stored with
--   needs_review = true and shown to the user - we never silently guess.
--
-- The `source` column says how sure we are of the string, not which company
-- printed it:
--   'common'     - standard clinical naming, used by essentially every lab
--   'indian_lab' - a variant characteristic of Indian lab report layouts
-- Attributing an exact string to a named laboratory would need real reports to
-- check against; see db/seed/GAPS.md.
-- ============================================================================

insert into public.biomarker_synonyms (synonym, biomarker_code, source)
values
  -- HB
  ('haemoglobin', 'HB', 'common'),
  ('hemoglobin', 'HB', 'common'),
  ('hb', 'HB', 'common'),
  ('hgb', 'HB', 'common'),
  ('haemoglobin (hb)', 'HB', 'common'),
  ('hemoglobin (hb)', 'HB', 'common'),
  ('haemoglobin - hb', 'HB', 'common'),
  ('blood haemoglobin', 'HB', 'common'),
  ('hemoglobin, blood', 'HB', 'common'),
  -- RBC
  ('rbc count', 'RBC', 'common'),
  ('red blood cell count', 'RBC', 'common'),
  ('total rbc count', 'RBC', 'common'),
  ('rbc', 'RBC', 'common'),
  ('erythrocyte count', 'RBC', 'common'),
  ('total rbc', 'RBC', 'common'),
  -- WBC
  ('wbc count', 'WBC', 'common'),
  ('total leucocyte count', 'WBC', 'common'),
  ('total leukocyte count', 'WBC', 'common'),
  ('tlc', 'WBC', 'indian_lab'),
  ('total wbc count', 'WBC', 'common'),
  ('white blood cell count', 'WBC', 'common'),
  ('leucocyte count', 'WBC', 'common'),
  ('total leucocyte count (tlc)', 'WBC', 'indian_lab'),
  ('wbc', 'WBC', 'common'),
  -- PLT
  ('platelet count', 'PLT', 'common'),
  ('platelets', 'PLT', 'common'),
  ('plt', 'PLT', 'common'),
  ('platelet count (plt)', 'PLT', 'common'),
  ('total platelet count', 'PLT', 'common'),
  -- PCV
  ('pcv', 'PCV', 'common'),
  ('packed cell volume', 'PCV', 'common'),
  ('packed cell volume (pcv)', 'PCV', 'common'),
  ('haematocrit', 'PCV', 'common'),
  ('hematocrit', 'PCV', 'common'),
  ('hct', 'PCV', 'common'),
  -- MCV
  ('mcv', 'MCV', 'common'),
  ('mean corpuscular volume', 'MCV', 'common'),
  ('mean cell volume', 'MCV', 'common'),
  -- MCH
  ('mch', 'MCH', 'common'),
  ('mean corpuscular haemoglobin', 'MCH', 'common'),
  ('mean corpuscular hemoglobin', 'MCH', 'common'),
  -- MCHC
  ('mchc', 'MCHC', 'common'),
  ('mean corpuscular haemoglobin concentration', 'MCHC', 'common'),
  ('mean corpuscular hemoglobin concentration', 'MCHC', 'common'),
  -- RDW
  ('rdw', 'RDW', 'common'),
  ('red cell distribution width', 'RDW', 'common'),
  ('rdw-cv', 'RDW', 'common'),
  ('rdw cv', 'RDW', 'common'),
  -- NEUT_PCT
  ('neutrophils', 'NEUT_PCT', 'common'),
  ('neutrophil', 'NEUT_PCT', 'common'),
  ('neutrophils %', 'NEUT_PCT', 'common'),
  ('segmented neutrophils', 'NEUT_PCT', 'common'),
  ('polymorphs', 'NEUT_PCT', 'indian_lab'),
  -- LYMPH_PCT
  ('lymphocytes', 'LYMPH_PCT', 'common'),
  ('lymphocyte', 'LYMPH_PCT', 'common'),
  ('lymphocytes %', 'LYMPH_PCT', 'common'),
  -- MONO_PCT
  ('monocytes', 'MONO_PCT', 'common'),
  ('monocyte', 'MONO_PCT', 'common'),
  ('monocytes %', 'MONO_PCT', 'common'),
  -- EOS_PCT
  ('eosinophils', 'EOS_PCT', 'common'),
  ('eosinophil', 'EOS_PCT', 'common'),
  ('eosinophils %', 'EOS_PCT', 'common'),
  -- BASO_PCT
  ('basophils', 'BASO_PCT', 'common'),
  ('basophil', 'BASO_PCT', 'common'),
  ('basophils %', 'BASO_PCT', 'common'),
  -- ESR
  ('esr', 'ESR', 'common'),
  ('erythrocyte sedimentation rate', 'ESR', 'common'),
  ('esr (westergren)', 'ESR', 'indian_lab'),
  ('erythrocyte sedimentation rate (esr)', 'ESR', 'common'),
  ('sedimentation rate', 'ESR', 'common'),
  -- RETIC_PCT
  ('reticulocyte count', 'RETIC_PCT', 'common'),
  ('retic count', 'RETIC_PCT', 'common'),
  ('reticulocytes', 'RETIC_PCT', 'common'),
  -- CHOL_TOTAL
  ('total cholesterol', 'CHOL_TOTAL', 'common'),
  ('cholesterol total', 'CHOL_TOTAL', 'common'),
  ('cholesterol - total', 'CHOL_TOTAL', 'common'),
  ('serum cholesterol', 'CHOL_TOTAL', 'common'),
  ('cholesterol', 'CHOL_TOTAL', 'common'),
  ('s. cholesterol', 'CHOL_TOTAL', 'indian_lab'),
  -- HDL
  ('hdl cholesterol', 'HDL', 'common'),
  ('hdl', 'HDL', 'common'),
  ('hdl - cholesterol', 'HDL', 'common'),
  ('high density lipoprotein', 'HDL', 'common'),
  ('cholesterol hdl', 'HDL', 'common'),
  ('hdl cholesterol - direct', 'HDL', 'common'),
  -- LDL
  ('ldl cholesterol', 'LDL', 'common'),
  ('ldl', 'LDL', 'common'),
  ('ldl - cholesterol', 'LDL', 'common'),
  ('low density lipoprotein', 'LDL', 'common'),
  ('cholesterol ldl', 'LDL', 'common'),
  ('ldl cholesterol - calculated', 'LDL', 'common'),
  -- VLDL
  ('vldl cholesterol', 'VLDL', 'common'),
  ('vldl', 'VLDL', 'common'),
  ('very low density lipoprotein', 'VLDL', 'common'),
  -- TRIG
  ('triglycerides', 'TRIG', 'common'),
  ('triglyceride', 'TRIG', 'common'),
  ('serum triglycerides', 'TRIG', 'common'),
  ('s. triglycerides', 'TRIG', 'indian_lab'),
  ('tg', 'TRIG', 'common'),
  -- NON_HDL
  ('non hdl cholesterol', 'NON_HDL', 'common'),
  ('non-hdl cholesterol', 'NON_HDL', 'common'),
  -- CHOL_HDL_RATIO
  ('total cholesterol / hdl ratio', 'CHOL_HDL_RATIO', 'common'),
  ('chol/hdl ratio', 'CHOL_HDL_RATIO', 'common'),
  ('tc/hdl ratio', 'CHOL_HDL_RATIO', 'common'),
  ('cholesterol / hdl ratio', 'CHOL_HDL_RATIO', 'common'),
  -- LDL_HDL_RATIO
  ('ldl / hdl ratio', 'LDL_HDL_RATIO', 'common'),
  ('ldl/hdl ratio', 'LDL_HDL_RATIO', 'common'),
  -- LIPOPROTEIN_A
  ('lipoprotein (a)', 'LIPOPROTEIN_A', 'common'),
  ('lp(a)', 'LIPOPROTEIN_A', 'common'),
  ('lipoprotein a', 'LIPOPROTEIN_A', 'common'),
  -- APO_B
  ('apolipoprotein b', 'APO_B', 'common'),
  ('apo b', 'APO_B', 'common'),
  ('apo-b', 'APO_B', 'common'),
  -- TSH
  ('tsh', 'TSH', 'common'),
  ('thyroid stimulating hormone', 'TSH', 'common'),
  ('tsh - ultrasensitive', 'TSH', 'indian_lab'),
  ('thyroid stimulating hormone (tsh)', 'TSH', 'common'),
  ('s. tsh', 'TSH', 'indian_lab'),
  ('tsh ultra sensitive', 'TSH', 'indian_lab'),
  -- FT3
  ('free t3', 'FT3', 'common'),
  ('ft3', 'FT3', 'common'),
  ('free tri-iodothyronine', 'FT3', 'common'),
  ('free triiodothyronine', 'FT3', 'common'),
  -- FT4
  ('free t4', 'FT4', 'common'),
  ('ft4', 'FT4', 'common'),
  ('free thyroxine', 'FT4', 'common'),
  -- T3_TOTAL
  ('total t3', 'T3_TOTAL', 'common'),
  ('t3', 'T3_TOTAL', 'common'),
  ('triiodothyronine', 'T3_TOTAL', 'common'),
  ('tri-iodothyronine (t3)', 'T3_TOTAL', 'common'),
  ('t3 - total', 'T3_TOTAL', 'common'),
  -- T4_TOTAL
  ('total t4', 'T4_TOTAL', 'common'),
  ('t4', 'T4_TOTAL', 'common'),
  ('thyroxine', 'T4_TOTAL', 'common'),
  ('thyroxine (t4)', 'T4_TOTAL', 'common'),
  ('t4 - total', 'T4_TOTAL', 'common'),
  -- ANTI_TPO
  ('anti tpo', 'ANTI_TPO', 'common'),
  ('anti-tpo', 'ANTI_TPO', 'common'),
  ('anti thyroid peroxidase antibody', 'ANTI_TPO', 'common'),
  ('tpo antibody', 'ANTI_TPO', 'common'),
  ('anti microsomal antibody', 'ANTI_TPO', 'common'),
  -- BILI_TOTAL
  ('total bilirubin', 'BILI_TOTAL', 'common'),
  ('bilirubin total', 'BILI_TOTAL', 'common'),
  ('bilirubin - total', 'BILI_TOTAL', 'common'),
  ('s. bilirubin (total)', 'BILI_TOTAL', 'indian_lab'),
  -- BILI_DIRECT
  ('direct bilirubin', 'BILI_DIRECT', 'common'),
  ('bilirubin direct', 'BILI_DIRECT', 'common'),
  ('bilirubin - direct', 'BILI_DIRECT', 'common'),
  ('conjugated bilirubin', 'BILI_DIRECT', 'common'),
  -- BILI_INDIRECT
  ('indirect bilirubin', 'BILI_INDIRECT', 'common'),
  ('bilirubin indirect', 'BILI_INDIRECT', 'common'),
  ('bilirubin - indirect', 'BILI_INDIRECT', 'common'),
  ('unconjugated bilirubin', 'BILI_INDIRECT', 'common'),
  -- ALT
  ('sgpt', 'ALT', 'indian_lab'),
  ('alt', 'ALT', 'common'),
  ('sgpt (alt)', 'ALT', 'indian_lab'),
  ('alt (sgpt)', 'ALT', 'indian_lab'),
  ('alanine transaminase', 'ALT', 'common'),
  ('alanine aminotransferase', 'ALT', 'common'),
  ('sgpt / alt', 'ALT', 'indian_lab'),
  -- AST
  ('sgot', 'AST', 'indian_lab'),
  ('ast', 'AST', 'common'),
  ('sgot (ast)', 'AST', 'indian_lab'),
  ('ast (sgot)', 'AST', 'indian_lab'),
  ('aspartate transaminase', 'AST', 'common'),
  ('aspartate aminotransferase', 'AST', 'common'),
  ('sgot / ast', 'AST', 'indian_lab'),
  -- ALP
  ('alkaline phosphatase', 'ALP', 'common'),
  ('alp', 'ALP', 'common'),
  ('alkaline phosphatase (alp)', 'ALP', 'common'),
  ('s. alkaline phosphatase', 'ALP', 'indian_lab'),
  -- GGT
  ('ggt', 'GGT', 'common'),
  ('gamma gt', 'GGT', 'common'),
  ('gamma glutamyl transferase', 'GGT', 'common'),
  ('gamma gt (ggt)', 'GGT', 'common'),
  ('ggtp', 'GGT', 'indian_lab'),
  -- PROTEIN_TOTAL
  ('total protein', 'PROTEIN_TOTAL', 'common'),
  ('protein total', 'PROTEIN_TOTAL', 'common'),
  ('serum total protein', 'PROTEIN_TOTAL', 'common'),
  ('s. protein (total)', 'PROTEIN_TOTAL', 'indian_lab'),
  -- ALBUMIN
  ('albumin', 'ALBUMIN', 'common'),
  ('serum albumin', 'ALBUMIN', 'common'),
  ('s. albumin', 'ALBUMIN', 'indian_lab'),
  -- GLOBULIN
  ('globulin', 'GLOBULIN', 'common'),
  ('serum globulin', 'GLOBULIN', 'common'),
  ('s. globulin', 'GLOBULIN', 'indian_lab'),
  -- AG_RATIO
  ('a/g ratio', 'AG_RATIO', 'common'),
  ('albumin globulin ratio', 'AG_RATIO', 'common'),
  ('albumin / globulin ratio', 'AG_RATIO', 'common'),
  -- UREA
  ('blood urea', 'UREA', 'common'),
  ('urea', 'UREA', 'common'),
  ('serum urea', 'UREA', 'common'),
  ('s. urea', 'UREA', 'indian_lab'),
  -- BUN
  ('bun', 'BUN', 'common'),
  ('blood urea nitrogen', 'BUN', 'common'),
  ('urea nitrogen', 'BUN', 'common'),
  -- CREATININE
  ('creatinine', 'CREATININE', 'common'),
  ('serum creatinine', 'CREATININE', 'common'),
  ('s. creatinine', 'CREATININE', 'indian_lab'),
  ('creatinine - serum', 'CREATININE', 'common'),
  -- EGFR
  ('egfr', 'EGFR', 'common'),
  ('estimated gfr', 'EGFR', 'common'),
  ('gfr estimated', 'EGFR', 'common'),
  ('e-gfr', 'EGFR', 'common'),
  -- URIC_ACID
  ('uric acid', 'URIC_ACID', 'common'),
  ('serum uric acid', 'URIC_ACID', 'common'),
  ('s. uric acid', 'URIC_ACID', 'indian_lab'),
  -- UACR
  ('urine albumin creatinine ratio', 'UACR', 'common'),
  ('acr', 'UACR', 'common'),
  ('microalbumin creatinine ratio', 'UACR', 'common'),
  -- GLUCOSE_FASTING
  ('fasting blood sugar', 'GLUCOSE_FASTING', 'indian_lab'),
  ('fbs', 'GLUCOSE_FASTING', 'indian_lab'),
  ('glucose fasting', 'GLUCOSE_FASTING', 'common'),
  ('fasting glucose', 'GLUCOSE_FASTING', 'common'),
  ('blood sugar fasting', 'GLUCOSE_FASTING', 'indian_lab'),
  ('glucose - fasting', 'GLUCOSE_FASTING', 'common'),
  ('fasting plasma glucose', 'GLUCOSE_FASTING', 'common'),
  ('sugar fasting', 'GLUCOSE_FASTING', 'indian_lab'),
  -- GLUCOSE_PP
  ('post prandial blood sugar', 'GLUCOSE_PP', 'indian_lab'),
  ('ppbs', 'GLUCOSE_PP', 'indian_lab'),
  ('pp blood sugar', 'GLUCOSE_PP', 'indian_lab'),
  ('glucose post prandial', 'GLUCOSE_PP', 'indian_lab'),
  ('post prandial glucose', 'GLUCOSE_PP', 'indian_lab'),
  ('blood sugar pp', 'GLUCOSE_PP', 'indian_lab'),
  ('glucose - pp (2 hrs)', 'GLUCOSE_PP', 'common'),
  ('2 hour postprandial glucose', 'GLUCOSE_PP', 'common'),
  -- GLUCOSE_RANDOM
  ('random blood sugar', 'GLUCOSE_RANDOM', 'indian_lab'),
  ('rbs', 'GLUCOSE_RANDOM', 'indian_lab'),
  ('glucose random', 'GLUCOSE_RANDOM', 'common'),
  ('blood sugar random', 'GLUCOSE_RANDOM', 'indian_lab'),
  -- HBA1C
  ('hba1c', 'HBA1C', 'common'),
  ('hba1c (glycosylated haemoglobin)', 'HBA1C', 'common'),
  ('glycosylated haemoglobin', 'HBA1C', 'common'),
  ('glycated haemoglobin', 'HBA1C', 'common'),
  ('glycosylated hemoglobin', 'HBA1C', 'common'),
  ('hb a1c', 'HBA1C', 'common'),
  ('a1c', 'HBA1C', 'common'),
  ('hba1c - glycated haemoglobin', 'HBA1C', 'common'),
  -- INSULIN_FASTING
  ('fasting insulin', 'INSULIN_FASTING', 'common'),
  ('insulin fasting', 'INSULIN_FASTING', 'common'),
  ('serum insulin (fasting)', 'INSULIN_FASTING', 'common'),
  -- VITD_25OH
  ('25 oh vitamin d', 'VITD_25OH', 'common'),
  ('vitamin d', 'VITD_25OH', 'common'),
  ('vitamin d (25-oh)', 'VITD_25OH', 'common'),
  ('vitamin d total', 'VITD_25OH', 'common'),
  ('25-hydroxy vitamin d', 'VITD_25OH', 'common'),
  ('25(oh)d', 'VITD_25OH', 'common'),
  ('vit d', 'VITD_25OH', 'indian_lab'),
  ('vit d (25-oh)', 'VITD_25OH', 'indian_lab'),
  ('vitamin d 25 hydroxy', 'VITD_25OH', 'common'),
  ('25-oh vitamin d total', 'VITD_25OH', 'common'),
  -- VITB12
  ('vitamin b12', 'VITB12', 'common'),
  ('b12', 'VITB12', 'common'),
  ('vit b12', 'VITB12', 'indian_lab'),
  ('cobalamin', 'VITB12', 'common'),
  ('vitamin b-12', 'VITB12', 'common'),
  ('serum vitamin b12', 'VITB12', 'common'),
  ('vitamin b12 (cobalamin)', 'VITB12', 'common'),
  -- FOLATE
  ('folate', 'FOLATE', 'common'),
  ('folic acid', 'FOLATE', 'common'),
  ('serum folate', 'FOLATE', 'common'),
  ('vitamin b9', 'FOLATE', 'common'),
  -- VITA
  ('vitamin a', 'VITA', 'common'),
  ('retinol', 'VITA', 'common'),
  ('serum retinol', 'VITA', 'common'),
  -- FERRITIN
  ('ferritin', 'FERRITIN', 'common'),
  ('serum ferritin', 'FERRITIN', 'common'),
  ('s. ferritin', 'FERRITIN', 'indian_lab'),
  ('ferritin - serum', 'FERRITIN', 'common'),
  -- IRON
  ('serum iron', 'IRON', 'common'),
  ('iron', 'IRON', 'common'),
  ('s. iron', 'IRON', 'indian_lab'),
  ('iron - serum', 'IRON', 'common'),
  -- TIBC
  ('tibc', 'TIBC', 'common'),
  ('total iron binding capacity', 'TIBC', 'common'),
  ('total iron binding capacity (tibc)', 'TIBC', 'common'),
  -- UIBC
  ('uibc', 'UIBC', 'common'),
  ('unsaturated iron binding capacity', 'UIBC', 'common'),
  -- TRANSFERRIN_SAT
  ('transferrin saturation', 'TRANSFERRIN_SAT', 'common'),
  ('% transferrin saturation', 'TRANSFERRIN_SAT', 'common'),
  ('transferrin saturation (%)', 'TRANSFERRIN_SAT', 'common'),
  ('iron saturation', 'TRANSFERRIN_SAT', 'common'),
  ('tsat', 'TRANSFERRIN_SAT', 'common'),
  -- CALCIUM
  ('calcium', 'CALCIUM', 'common'),
  ('serum calcium', 'CALCIUM', 'common'),
  ('s. calcium', 'CALCIUM', 'indian_lab'),
  ('total calcium', 'CALCIUM', 'common'),
  ('calcium - total', 'CALCIUM', 'common'),
  -- CALCIUM_IONIZED
  ('ionised calcium', 'CALCIUM_IONIZED', 'common'),
  ('ionized calcium', 'CALCIUM_IONIZED', 'common'),
  ('calcium ionised', 'CALCIUM_IONIZED', 'common'),
  -- PHOSPHORUS
  ('phosphorus', 'PHOSPHORUS', 'common'),
  ('serum phosphorus', 'PHOSPHORUS', 'common'),
  ('inorganic phosphorus', 'PHOSPHORUS', 'common'),
  ('phosphate', 'PHOSPHORUS', 'common'),
  -- MAGNESIUM
  ('magnesium', 'MAGNESIUM', 'common'),
  ('serum magnesium', 'MAGNESIUM', 'common'),
  ('s. magnesium', 'MAGNESIUM', 'indian_lab'),
  -- SODIUM
  ('sodium', 'SODIUM', 'common'),
  ('serum sodium', 'SODIUM', 'common'),
  ('s. sodium', 'SODIUM', 'indian_lab'),
  ('na+', 'SODIUM', 'common'),
  ('sodium (na)', 'SODIUM', 'common'),
  -- POTASSIUM
  ('potassium', 'POTASSIUM', 'common'),
  ('serum potassium', 'POTASSIUM', 'common'),
  ('s. potassium', 'POTASSIUM', 'indian_lab'),
  ('k+', 'POTASSIUM', 'common'),
  ('potassium (k)', 'POTASSIUM', 'common'),
  -- CHLORIDE
  ('chloride', 'CHLORIDE', 'common'),
  ('serum chloride', 'CHLORIDE', 'common'),
  ('s. chloride', 'CHLORIDE', 'indian_lab'),
  ('chloride (cl)', 'CHLORIDE', 'common'),
  -- BICARBONATE
  ('bicarbonate', 'BICARBONATE', 'common'),
  ('serum bicarbonate', 'BICARBONATE', 'common'),
  ('hco3', 'BICARBONATE', 'common'),
  ('co2 (bicarbonate)', 'BICARBONATE', 'common'),
  -- CRP_HS
  ('hs crp', 'CRP_HS', 'common'),
  ('hs-crp', 'CRP_HS', 'common'),
  ('high sensitivity crp', 'CRP_HS', 'common'),
  ('crp (high sensitivity)', 'CRP_HS', 'common'),
  ('c reactive protein (hs)', 'CRP_HS', 'common'),
  -- HOMOCYSTEINE
  ('homocysteine', 'HOMOCYSTEINE', 'common'),
  ('serum homocysteine', 'HOMOCYSTEINE', 'common'),
  ('total homocysteine', 'HOMOCYSTEINE', 'common'),
  -- PSA
  ('psa', 'PSA', 'common'),
  ('prostate specific antigen', 'PSA', 'common'),
  ('total psa', 'PSA', 'common'),
  ('psa total', 'PSA', 'common'),
  -- CPK
  ('cpk', 'CPK', 'common'),
  ('creatine phosphokinase', 'CPK', 'common'),
  ('ck total', 'CPK', 'common'),
  ('creatine kinase', 'CPK', 'common'),
  -- AMYLASE
  ('amylase', 'AMYLASE', 'common'),
  ('serum amylase', 'AMYLASE', 'common'),
  -- LIPASE
  ('lipase', 'LIPASE', 'common'),
  ('serum lipase', 'LIPASE', 'common'),
  -- LDH
  ('ldh', 'LDH', 'common'),
  ('lactate dehydrogenase', 'LDH', 'common'),
  ('lactic dehydrogenase', 'LDH', 'common'),
  -- CORTISOL_AM
  ('cortisol', 'CORTISOL_AM', 'common'),
  ('serum cortisol', 'CORTISOL_AM', 'common'),
  ('cortisol - morning', 'CORTISOL_AM', 'common'),
  ('cortisol (am)', 'CORTISOL_AM', 'common'),
  -- PTH
  ('pth', 'PTH', 'common'),
  ('parathyroid hormone', 'PTH', 'common'),
  ('intact pth', 'PTH', 'common'),
  ('pth intact', 'PTH', 'common'),
  -- TESTOSTERONE_TOTAL
  ('total testosterone', 'TESTOSTERONE_TOTAL', 'common'),
  ('testosterone', 'TESTOSTERONE_TOTAL', 'common'),
  ('testosterone total', 'TESTOSTERONE_TOTAL', 'common'),
  -- PROLACTIN
  ('prolactin', 'PROLACTIN', 'common'),
  ('serum prolactin', 'PROLACTIN', 'common'),
  ('prl', 'PROLACTIN', 'common')
on conflict (synonym) do nothing;

-- ---------------------------------------------------------------------------
-- Absolute neutrophil count and serum zinc. Added alongside the codes in
-- 200_biomarkers.sql; without these a report printing "ANC" would never reach
-- the neutropenia red-flag rule.
-- ---------------------------------------------------------------------------
insert into public.biomarker_synonyms (synonym, biomarker_code, source) values
  ('absolute neutrophil count', 'NEUTROPHILS_ABS', 'common'),
  ('anc', 'NEUTROPHILS_ABS', 'common'),
  ('neutrophil absolute count', 'NEUTROPHILS_ABS', 'indian_lab'),
  ('absolute neutrophils', 'NEUTROPHILS_ABS', 'common'),
  ('neutrophils absolute', 'NEUTROPHILS_ABS', 'indian_lab'),
  ('neutrophil count absolute', 'NEUTROPHILS_ABS', 'indian_lab'),
  ('serum zinc', 'ZINC', 'common'),
  ('zinc', 'ZINC', 'common'),
  ('zinc serum', 'ZINC', 'indian_lab'),
  ('zn', 'ZINC', 'common')
on conflict (synonym) do nothing;

-- ---------------------------------------------------------------------------
-- Names taken verbatim from a real 18-page AHC hybrid panel issued in Hyderabad
-- in September 2026. Half of the test names on that report did not match any
-- synonym seeded from general knowledge, which is why report-derived synonyms
-- matter more than plausible-sounding ones. Note the missing and irregular
-- spacing ("bilirubin -direct", "unsat.iron-binding capacity(uibc)") -- that is
-- how the lab prints it, and the normaliser has to cope with it.
-- ---------------------------------------------------------------------------
insert into public.biomarker_synonyms (synonym, biomarker_code, source) values
  ('alanine transaminase (sgpt)', 'ALT', 'indian_lab'),
  ('aspartate aminotransferase (sgot)', 'AST', 'indian_lab'),
  ('gamma glutamyl transferase (ggt)', 'GGT', 'indian_lab'),
  ('blood urea nitrogen (bun)', 'BUN', 'indian_lab'),
  ('est. glomerular filtration rate (egfr)', 'EGFR', 'indian_lab'),
  ('albumin - serum', 'ALBUMIN', 'indian_lab'),
  ('protein - total', 'PROTEIN_TOTAL', 'indian_lab'),
  ('bilirubin - total', 'BILI_TOTAL', 'indian_lab'),
  ('bilirubin -direct', 'BILI_DIRECT', 'indian_lab'),
  ('bilirubin (indirect)', 'BILI_INDIRECT', 'indian_lab'),
  ('creatinine - serum', 'CREATININE', 'indian_lab'),
  ('serum globulin', 'GLOBULIN', 'indian_lab'),
  ('serum alb/globulin ratio', 'AG_RATIO', 'indian_lab'),
  ('ldl cholesterol - direct', 'LDL', 'indian_lab'),
  ('hdl cholesterol - direct', 'HDL', 'indian_lab'),
  ('tc/ hdl cholesterol ratio', 'CHOL_HDL_RATIO', 'indian_lab'),
  ('hdl / ldl ratio', 'LDL_HDL_RATIO', 'indian_lab'),
  ('trig / hdl ratio', 'TRIG_HDL_RATIO', 'indian_lab'),
  ('fasting blood sugar(glucose)', 'GLUCOSE_FASTING', 'indian_lab'),
  ('average blood glucose (abg)', 'AVG_GLUCOSE', 'indian_lab'),
  ('tsh - ultrasensitive', 'TSH', 'indian_lab'),
  ('total triiodothyronine (t3)', 'T3_TOTAL', 'indian_lab'),
  ('total thyroxine (t4)', 'T4_TOTAL', 'indian_lab'),
  ('25-oh vitamin d (total)', 'VITD_25OH', 'indian_lab'),
  ('total iron binding capacity (tibc)', 'TIBC', 'indian_lab'),
  ('unsat.iron-binding capacity(uibc)', 'UIBC', 'indian_lab'),
  ('prostate specific antigen (psa)', 'PSA', 'indian_lab'),
  ('platelet distribution width(pdw)', 'PDW', 'indian_lab'),
  ('platelet distribution width', 'PDW', 'common'),
  ('pdw', 'PDW', 'common'),
  ('mean platelet volume', 'MPV', 'common'),
  ('mpv', 'MPV', 'common'),
  ('total rbc', 'RBC', 'indian_lab'),
  ('erythrocyte sedimentation rate (esr)', 'ESR', 'indian_lab')
on conflict (synonym) do nothing;



-- Check: this must print 353.
select count(*) as synonyms_loaded from public.biomarker_synonyms;

-- Check: no synonym points at a biomarker that does not exist (0 rows expected).
select s.synonym, s.biomarker_code
from public.biomarker_synonyms s
left join public.biomarkers b on b.code = s.biomarker_code
where b.code is null;

-- --------------------------------------------------------------------------
-- source: db/seed/202_reference_ranges.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 202_reference_ranges.sql
-- HealthPulse seed - deterministic classification thresholds
--
-- Run AFTER 200_biomarkers.sql. Safe to run more than once.
--
-- ###########################################################################
-- #  SAFETY RULE FOR THIS FILE                                              #
-- #                                                                         #
-- #  Every row carries a source_citation naming the guideline the numbers   #
-- #  came from. No threshold in this file was invented, estimated or        #
-- #  averaged. Where a trustworthy published threshold could not be named,  #
-- #  THE ROW WAS LEFT OUT and the omission was written into                 #
-- #  db/seed/GAPS.md for a clinician to fill in.                            #
-- #                                                                         #
-- #  That is why some biomarkers below have a low but no high, or only a    #
-- #  critical value. A missing number means "we do not know", which the     #
-- #  classifier must treat as "cannot classify this direction" - never as   #
-- #  "normal".                                                              #
-- #                                                                         #
-- #  Do not add a row here without a citation. Do not change a number       #
-- #  without changing its citation.                                         #
-- ###########################################################################
--
-- HOW THE SIX NUMBERS ARE READ (docs/04-ai-pipeline.md stage 4)
--
--   The six thresholds always read in this order, ignoring nulls:
--     critical_low <= low <= borderline_low <= borderline_high <= high <= critical_high
--
--   Classification, first match wins:
--     value <  critical_low     -> critical_low
--     value <  low              -> low
--     value <  borderline_low   -> borderline_low
--     value >  critical_high    -> critical_high
--     value >  high             -> high
--     value >  borderline_high  -> borderline_high
--     otherwise                 -> normal
--
--   A null threshold means that step is skipped. It does NOT mean "normal".
--
-- UNITS
--   Every number below is in the biomarker's canonical_unit from
--   200_biomarkers.sql. Convert the lab's value BEFORE comparing.
--
-- MATCHING A ROW TO A USER
--   sex:        'male' / 'female' / 'any'. Prefer the sex-specific row.
--   age band:   age_min <= age <= age_max, in whole years.
--   pregnancy:  null = applies whatever the pregnancy status.
--               A true/false row overrides the null row for that user.
-- ============================================================================

insert into public.reference_ranges (
  biomarker_code, sex, age_min, age_max, pregnancy,
  critical_low, low, borderline_low, borderline_high, high, critical_high,
  source_citation)
values

-- ---------------------------------------------------------------------------
-- HAEMOGLOBIN - WHO anaemia thresholds
-- WHO. Haemoglobin concentrations for the diagnosis of anaemia and assessment
-- of severity. Vitamin and Mineral Nutrition Information System.
-- Geneva, World Health Organization, 2011 (WHO/NMH/NHD/MNM/11.1).
-- Bands used: severe / moderate / mild anaemia -> critical_low / low / borderline_low.
-- NOTE: docs/04-ai-pipeline.md uses Hb < 7 g/dL as the `urgent` escalation for
-- adults, which is stricter than WHO's severe-anaemia cut-off of 8 g/dL. Both
-- are kept: 8.0 classifies the value, 7.0 escalates. See db/seed/GAPS.md.
-- ---------------------------------------------------------------------------
('HB', 'male',   15, 120, null, 8.0, 11.0, 13.0, null, null, null,
 'WHO 2011 (WHO/NMH/NHD/MNM/11.1), non-pregnant males 15+ years: normal >=13.0 g/dL; mild anaemia 11.0-12.9; moderate 8.0-10.9; severe <8.0 g/dL.'),

('HB', 'female', 15, 120, false, 8.0, 11.0, 12.0, null, null, null,
 'WHO 2011 (WHO/NMH/NHD/MNM/11.1), non-pregnant females 15+ years: normal >=12.0 g/dL; mild anaemia 11.0-11.9; moderate 8.0-10.9; severe <8.0 g/dL.'),

('HB', 'female', 15, 120, true, 7.0, 10.0, 11.0, null, null, null,
 'WHO 2011 (WHO/NMH/NHD/MNM/11.1), pregnant women: normal >=11.0 g/dL; mild anaemia 10.0-10.9; moderate 7.0-9.9; severe <7.0 g/dL.'),

('HB', 'any', 0, 4, null, 7.0, 10.0, 11.0, null, null, null,
 'WHO 2011 (WHO/NMH/NHD/MNM/11.1), children 6-59 months: normal >=11.0 g/dL; mild anaemia 10.0-10.9; moderate 7.0-9.9; severe <7.0 g/dL.'),

('HB', 'any', 5, 11, null, 8.0, 11.0, 11.5, null, null, null,
 'WHO 2011 (WHO/NMH/NHD/MNM/11.1), children 5-11 years: normal >=11.5 g/dL; mild anaemia 11.0-11.4; moderate 8.0-10.9; severe <8.0 g/dL.'),

('HB', 'any', 12, 14, null, 8.0, 11.0, 12.0, null, null, null,
 'WHO 2011 (WHO/NMH/NHD/MNM/11.1), children 12-14 years: normal >=12.0 g/dL; mild anaemia 11.0-11.9; moderate 8.0-10.9; severe <8.0 g/dL.'),

-- ---------------------------------------------------------------------------
-- GLYCAEMIC - American Diabetes Association
-- ---------------------------------------------------------------------------
('GLUCOSE_FASTING', 'any', 18, 120, null, 54, 70, null, 99, 125, 300,
 'American Diabetes Association, Standards of Care in Diabetes, Classification and Diagnosis: normal fasting plasma glucose <100 mg/dL; impaired fasting glucose 100-125 mg/dL; diabetes >=126 mg/dL. Hypoglycaemia: ADA/EASD Level 1 alert value <=70 mg/dL, Level 2 clinically significant <54 mg/dL. Critical high 300 mg/dL is the HealthPulse urgent red flag from docs/04-ai-pipeline.md stage 5.'),

('GLUCOSE_PP', 'any', 18, 120, null, null, null, null, 139, 199, null,
 'American Diabetes Association / WHO 75 g oral glucose tolerance test, 2-hour plasma glucose: normal <140 mg/dL; impaired glucose tolerance 140-199 mg/dL; diabetes >=200 mg/dL.'),

('GLUCOSE_RANDOM', 'any', 18, 120, null, null, null, null, null, 199, null,
 'American Diabetes Association, Standards of Care in Diabetes, Classification and Diagnosis: random plasma glucose >=200 mg/dL with classic symptoms of hyperglycaemia is diagnostic of diabetes.'),

('HBA1C', 'any', 18, 120, null, null, null, null, 5.6, 6.4, null,
 'American Diabetes Association, Standards of Care in Diabetes, Classification and Diagnosis: normal HbA1c <5.7%; prediabetes 5.7-6.4%; diabetes >=6.5%. docs/04-ai-pipeline.md escalates a first HbA1c >=6.5% to see_doctor_soon.'),

-- ---------------------------------------------------------------------------
-- LIPIDS - NCEP Adult Treatment Panel III
-- National Cholesterol Education Program (NCEP) Expert Panel on Detection,
-- Evaluation, and Treatment of High Blood Cholesterol in Adults (Adult
-- Treatment Panel III) Final Report. Circulation, 2002.
-- ---------------------------------------------------------------------------
('CHOL_TOTAL', 'any', 18, 120, null, null, null, null, 199, 239, null,
 'NCEP ATP III total cholesterol categories: desirable <200 mg/dL; borderline high 200-239 mg/dL; high >=240 mg/dL.'),

('LDL', 'any', 18, 120, null, null, null, null, 129, 159, 189,
 'NCEP ATP III LDL-cholesterol categories: optimal <100 mg/dL; near/above optimal 100-129; borderline high 130-159; high 160-189; very high >=190 mg/dL.'),

('HDL', 'male', 18, 120, null, null, 40, null, null, null, null,
 'NCEP ATP III: HDL-cholesterol <40 mg/dL is a categorical major risk factor for coronary heart disease in men.'),

('HDL', 'female', 18, 120, null, null, 50, null, null, null, null,
 'NCEP ATP III metabolic syndrome criteria: low HDL-cholesterol is <40 mg/dL in men and <50 mg/dL in women.'),

('TRIG', 'any', 18, 120, null, null, null, null, 149, 199, 499,
 'NCEP ATP III triglyceride categories: normal <150 mg/dL; borderline high 150-199; high 200-499; very high >=500 mg/dL (very high carries a risk of acute pancreatitis).'),

('NON_HDL', 'any', 18, 120, null, null, null, null, 129, 159, null,
 'NCEP ATP III: the non-HDL-cholesterol goal is the LDL-cholesterol goal plus 30 mg/dL, giving <130 mg/dL for moderate-risk adults and <160 mg/dL for lower-risk adults. This target is risk-stratified - see db/seed/GAPS.md.'),

-- ---------------------------------------------------------------------------
-- THYROID
-- ---------------------------------------------------------------------------
('TSH', 'any', 18, 120, null, null, 0.45, null, 4.5, 10.0, null,
 'American Thyroid Association guidelines for the treatment of hypothyroidism (Jonklaas et al., Thyroid 2014) and the ATA/AACE definition of subclinical disease: TSH above the upper reference limit of approximately 4.5 mIU/L with a normal free T4 is subclinical hypothyroidism; TSH >10 mIU/L is overt hypothyroidism warranting treatment; TSH below the lower reference limit of approximately 0.45 mIU/L indicates thyrotoxicosis. docs/04-ai-pipeline.md escalates TSH >10 to see_doctor_soon.'),

-- ---------------------------------------------------------------------------
-- LIVER
-- ---------------------------------------------------------------------------
('ALT', 'male', 18, 120, null, null, null, null, null, 33, null,
 'ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries (Kwo, Cohen, Lim; Am J Gastroenterol 2017): the true healthy upper limit of normal for ALT is 29-33 IU/L in males. The upper bound of that range is used here.'),

('ALT', 'female', 18, 120, null, null, null, null, null, 25, null,
 'ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries (Kwo, Cohen, Lim; Am J Gastroenterol 2017): the true healthy upper limit of normal for ALT is 19-25 IU/L in females. The upper bound of that range is used here.'),

-- ---------------------------------------------------------------------------
-- KIDNEY
-- ---------------------------------------------------------------------------
('EGFR', 'any', 18, 120, null, 15, 60, 90, null, null, null,
 'KDIGO 2012 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease, GFR categories: G1 >=90; G2 60-89 (mildly decreased); G3a-G4 15-59 (moderately to severely decreased); G5 <15 mL/min/1.73m2 (kidney failure).'),

('URIC_ACID', 'any', 18, 120, null, null, null, null, 6.0, 6.8, null,
 'American College of Rheumatology Guideline for the Management of Gout (FitzGerald et al., Arthritis Care Res 2020) recommends a serum urate treatment target of <6 mg/dL. Hyperuricaemia is conventionally defined by the limit of urate solubility in serum, approximately 6.8 mg/dL.'),

-- ---------------------------------------------------------------------------
-- VITAMINS AND IRON
-- ---------------------------------------------------------------------------
('VITD_25OH', 'any', 18, 120, null, null, 20, 30, null, null, null,
 'Endocrine Society Clinical Practice Guideline, Evaluation, Treatment, and Prevention of Vitamin D Deficiency (Holick et al., J Clin Endocrinol Metab 2011): deficiency 25(OH)D <20 ng/mL; insufficiency 21-29 ng/mL; sufficiency >=30 ng/mL. The US Institute of Medicine (2011) uses a lower cut-off of 20 ng/mL for sufficiency - see db/seed/GAPS.md.'),

('VITB12', 'any', 18, 120, null, null, 200, 300, null, null, null,
 'British Committee for Standards in Haematology, Guidelines for the diagnosis and treatment of cobalamin and folate disorders (Devalia, Hamilton, Molloy; Br J Haematol 2014): serum cobalamin below approximately 200 ng/L (pg/mL) indicates deficiency; 200-300 ng/L is an indeterminate/borderline zone requiring a second-line test such as methylmalonic acid.'),

('FOLATE', 'any', 18, 120, null, null, 3.0, null, null, null, null,
 'British Committee for Standards in Haematology, Guidelines for the diagnosis and treatment of cobalamin and folate disorders (Devalia, Hamilton, Molloy; Br J Haematol 2014): serum folate below approximately 7 nmol/L (3 ug/L, i.e. 3 ng/mL) indicates folate deficiency.'),

('FERRITIN', 'any', 18, 120, null, null, 15, 30, null, null, null,
 'WHO guideline on use of ferritin concentrations to assess iron status in individuals and populations (2020): ferritin <15 ug/L indicates iron deficiency in adults. British Society of Gastroenterology guidelines for the management of iron deficiency anaemia (Snook et al., Gut 2021): ferritin <30 ug/L confirms iron deficiency. ng/mL is numerically equal to ug/L.'),

-- ---------------------------------------------------------------------------
-- CRITICAL-VALUE-ONLY ROWS
-- These biomarkers have no seeded normal interval because a citable,
-- assay-independent one could not be named. Only the red-flag threshold is
-- stored, so the app can still escalate. See db/seed/GAPS.md.
-- ---------------------------------------------------------------------------
('POTASSIUM', 'any', 18, 120, null, 2.5, null, null, null, null, 6.0,
 'HealthPulse red-flag thresholds, docs/04-ai-pipeline.md stage 5: serum potassium <2.5 or >6.0 mmol/L is an urgent escalation. The normal reference interval for potassium is assay- and laboratory-dependent and is deliberately NOT seeded - see db/seed/GAPS.md.'),

('PLT', 'any', 18, 120, null, 50, null, null, null, null, null,
 'HealthPulse red-flag thresholds, docs/04-ai-pipeline.md stage 5: platelets <50 x10^3/uL is an urgent escalation. This agrees with NCI CTCAE v5.0, where a platelet count <50.0 x10^9/L is grade 3 or worse thrombocytopenia. The normal platelet interval is laboratory-dependent and is deliberately NOT seeded - see db/seed/GAPS.md.'),

-- ---------------------------------------------------------------------------
-- INFLAMMATION
-- ---------------------------------------------------------------------------
('CRP_HS', 'any', 18, 120, null, null, null, null, 1.0, 3.0, null,
 'AHA/CDC Scientific Statement, Markers of Inflammation and Cardiovascular Disease (Pearson et al., Circulation 2003): hs-CRP <1.0 mg/L low relative cardiovascular risk; 1.0-3.0 mg/L average risk; >3.0 mg/L high risk.')

on conflict (biomarker_code, sex, age_min, age_max, pregnancy) do nothing;


-- ============================================================================
-- CHECKS
-- ============================================================================

-- 1. How many ranges were loaded, and for how many biomarkers.
select count(*) as ranges_loaded,
       count(distinct biomarker_code) as biomarkers_covered
from public.reference_ranges;

-- 2. Every row must have a citation. This must return 0 rows.
select id, biomarker_code
from public.reference_ranges
where source_citation is null or length(btrim(source_citation)) = 0;

-- 3. Which seeded biomarkers still have NO range at all. These are the gaps a
--    clinician has to fill; they are listed in db/seed/GAPS.md.
select b.code, b.display_name, b.category
from public.biomarkers b
left join public.reference_ranges r on r.biomarker_code = b.code
where r.id is null
order by b.category, b.code;

-- --------------------------------------------------------------------------
-- source: db/seed/203_rda_targets.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 203_rda_targets.sql
-- Energy is stored as 'kcal' to match foods.per_100g. One spelling across the
-- whole system, so gap arithmetic cannot silently miss it.
-- HealthPulse seed - daily nutrient targets for Indian adults
--
-- Run AFTER the migrations. Safe to run more than once.
--
-- Source for every row: Indian Council of Medical Research - National Institute
-- of Nutrition (ICMR-NIN). "Nutrient Requirements for Indians: Recommended
-- Dietary Allowances (RDA) and Estimated Average Requirements (EAR)", 2020.
-- Reference adult man 65 kg, reference adult woman 55 kg.
--
-- ###########################################################################
-- #  Same rule as the reference ranges: cite or omit.                       #
-- #  Only nutrients whose ICMR-NIN 2020 value could be stated with          #
-- #  confidence are seeded. Fibre, vitamin A, vitamin C, magnesium, iodine, #
-- #  selenium, the pregnancy and lactation increments, the 60+ adjustments  #
-- #  and every child/adolescent band are LEFT OUT and listed in             #
-- #  db/seed/GAPS.md for a dietitian to fill in from the printed table.     #
-- ###########################################################################
--
-- HOW THE PLANNER USES THIS (docs/04-ai-pipeline.md stage 6, "GAPS" block)
--   Pick the row matching the user's sex, age and activity_level; where
--   activity_level = 'any' the target does not vary with activity. Compare the
--   target with what the user actually ate (food_logs joined to foods) to get
--   "vitamin D 78% below target".
--
-- ACTIVITY LEVELS are ICMR-NIN's own three groups and must match
--   health_profiles.activity_level exactly: sedentary | moderate | heavy.
--
-- NUTRIENT KEYS match the keys used inside foods.per_100g.
-- ============================================================================

insert into public.rda_targets
  (nutrient, sex, age_min, age_max, activity_level, amount, unit, source, source_citation)
values

-- ------------------------------------------------------------------ energy --
('kcal',        'male',   19, 59, 'sedentary', 2110, 'kcal', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: reference adult man (65 kg), sedentary work, 2110 kcal/day.'),
('kcal',        'male',   19, 59, 'moderate',  2710, 'kcal', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: reference adult man (65 kg), moderate work, 2710 kcal/day.'),
('kcal',        'male',   19, 59, 'heavy',     3470, 'kcal', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: reference adult man (65 kg), heavy work, 3470 kcal/day.'),
('kcal',        'female', 19, 59, 'sedentary', 1660, 'kcal', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: reference adult woman (55 kg), sedentary work, 1660 kcal/day.'),
('kcal',        'female', 19, 59, 'moderate',  2130, 'kcal', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: reference adult woman (55 kg), moderate work, 2130 kcal/day.'),
('kcal',        'female', 19, 59, 'heavy',     2720, 'kcal', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: reference adult woman (55 kg), heavy work, 2720 kcal/day.'),

-- ----------------------------------------------------------------- protein --
-- Protein requirement is set per kg of body weight (0.83 g/kg/day), not by
-- activity level, so activity_level is 'any'.
('protein_g', 'male',   19, 59, 'any', 54, 'g', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for protein, reference adult man (65 kg), 54 g/day, derived from 0.83 g/kg body weight/day.'),
('protein_g', 'female', 19, 59, 'any', 46, 'g', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for protein, reference adult woman (55 kg), 46 g/day, derived from 0.83 g/kg body weight/day.'),

-- ----------------------------------------------------------------- calcium --
('calcium_mg', 'any', 19, 59, 'any', 1000, 'mg', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for calcium, adult men and women, 1000 mg/day.'),

-- -------------------------------------------------------------------- iron --
-- The higher figure for women reflects menstrual losses.
('iron_mg', 'male',   19, 59, 'any', 19, 'mg', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for iron, adult man, 19 mg/day.'),
('iron_mg', 'female', 19, 59, 'any', 29, 'mg', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for iron, adult woman of reproductive age, 29 mg/day.'),

-- -------------------------------------------------------------------- zinc --
('zinc_mg', 'male',   19, 59, 'any', 17, 'mg', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for zinc, adult man, 17 mg/day.'),
('zinc_mg', 'female', 19, 59, 'any', 13, 'mg', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for zinc, adult woman, 13 mg/day.'),

-- --------------------------------------------------------------- vitamin D --
('vitamin_d_ug', 'any', 19, 59, 'any', 15, 'ug', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for vitamin D, adults, 600 IU/day, which is 15 micrograms of cholecalciferol per day.'),

-- ------------------------------------------------------------- vitamin B12 --
('b12_ug', 'any', 19, 59, 'any', 2.2, 'ug', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for vitamin B12, adults, 2.2 micrograms/day.'),

-- ------------------------------------------------------------------ folate --
('folate_ug', 'any', 19, 59, 'any', 300, 'ug', 'ICMR-NIN 2020',
 'ICMR-NIN, Nutrient Requirements for Indians 2020: RDA for folate, adults, 300 micrograms/day.')

on conflict (nutrient, sex, age_min, age_max, activity_level) do nothing;


-- ============================================================================
-- CHECKS
-- ============================================================================

-- 1. How many targets were loaded.
select count(*) as rda_targets_loaded,
       count(distinct nutrient) as nutrients_covered
from public.rda_targets;

-- 2. Every row must have a citation. This must return 0 rows.
select id, nutrient
from public.rda_targets
where source_citation is null or length(btrim(source_citation)) = 0;

-- 3. What a moderately active 32-year-old man should be aiming for.
select nutrient, amount, unit
from public.rda_targets
where sex in ('male', 'any')
  and 32 between age_min and age_max
  and activity_level in ('moderate', 'any')
order by nutrient;

-- --------------------------------------------------------------------------
-- source: db/seed/204_foods_starter.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- 204_foods_starter.sql
-- HealthPulse seed - starter food composition table
--
-- Run AFTER the migrations. Safe to run more than once.
--
-- 147 common Indian foods, per 100 g of edible portion, raw unless the name says
-- otherwise.
--
-- ###########################################################################
-- #  READ THIS BEFORE YOU TRUST A NUMBER IN THIS FILE                       #
-- #                                                                         #
-- #  Every row is loaded with  source = 'PROVISIONAL'.                      #
-- #                                                                         #
-- #  That is deliberate and it is not a placeholder to be quietly deleted.  #
-- #  These values are typical published composition figures for each food.  #
-- #  They have NOT been checked line by line against IFCT 2017 or USDA      #
-- #  FoodData Central, and they carry no IFCT or USDA record number.        #
-- #  Claiming source = 'IFCT2017' without that check would be inventing a   #
-- #  provenance, which is exactly what CLAUDE.md forbids.                   #
-- #                                                                         #
-- #  They are good enough to build and test the planner against. Before any #
-- #  real user is shown a nutrient number, run a verified import and flip   #
-- #  each row to source = 'IFCT2017' or 'USDA' with the real source_id.     #
-- #  db/seed/GAPS.md has the full list of what to check.                    #
-- ###########################################################################
--
-- WHAT IS AND IS NOT IN per_100g
--   Always present: kcal, protein_g, fat_g, carb_g, fibre_g.
--   Micronutrients (iron_mg, calcium_mg, folate_ug, b12_ug, vitamin_d_ug,
--   vitamin_a_ug, vitamin_c_mg, magnesium_mg, zinc_mg, potassium_mg) are
--   present ONLY where the food is a well-known source of that nutrient and the
--   figure is a widely published one.
--
--   A MISSING KEY MEANS "WE DO NOT KNOW", NOT "ZERO". The backend must treat an
--   absent key as unknown and must not add it into a daily total as 0.
--
-- diet_flags   veg, vegan, egg, non_veg, jain, gluten_free, high_protein,
--              high_fibre, high_iron, high_calcium
--              'jain' excludes root vegetables, onion, garlic, ginger and honey.
--              'gluten_free' is not claimed for oats (cross-contamination).
-- allergens    milk, egg, peanut, tree_nut, sesame, soy, fish, shellfish,
--              gluten, mustard.  This list is a HARD filter against the
--              allergies table - never a suggestion.
-- ============================================================================

insert into public.foods
  (name, name_local, food_group, per_100g, diet_flags, allergens, region, source, source_id)
values
  -- cereal_millet
  ('Rice, raw milled', 'Chawal', 'cereal_millet',
   '{"kcal": 345, "protein_g": 6.8, "fat_g": 0.5, "carb_g": 78.2, "fibre_g": 0.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'rice_raw_milled'),
  ('Rice, parboiled milled', 'Ukda chawal', 'cereal_millet',
   '{"kcal": 346, "protein_g": 6.5, "fat_g": 0.6, "carb_g": 78.0, "fibre_g": 0.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'rice_parboiled'),
  ('Rice, brown', 'Brown chawal', 'cereal_millet',
   '{"kcal": 362, "protein_g": 7.5, "fat_g": 2.7, "carb_g": 76.0, "fibre_g": 3.5, "magnesium_mg": 143}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'rice_brown'),
  ('Wheat flour, wholemeal (atta)', 'Gehun atta', 'cereal_millet',
   '{"kcal": 341, "protein_g": 12.1, "fat_g": 1.7, "carb_g": 69.4, "fibre_g": 11.0, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'high_fibre', 'high_iron']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'wheat_flour_atta'),
  ('Wheat flour, refined (maida)', 'Maida', 'cereal_millet',
   '{"kcal": 348, "protein_g": 10.4, "fat_g": 0.8, "carb_g": 74.0, "fibre_g": 2.7}'::jsonb,
   array['veg', 'vegan', 'jain']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'maida'),
  ('Semolina (rava / suji)', 'Rava', 'cereal_millet',
   '{"kcal": 348, "protein_g": 10.4, "fat_g": 1.0, "carb_g": 74.8, "fibre_g": 3.5}'::jsonb,
   array['veg', 'vegan', 'jain']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'semolina'),
  ('Rice flakes (poha)', 'Poha', 'cereal_millet',
   '{"kcal": 346, "protein_g": 6.6, "fat_g": 1.2, "carb_g": 77.3, "fibre_g": 2.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'poha'),
  ('Bread, wholemeal', 'Brown bread', 'cereal_millet',
   '{"kcal": 247, "protein_g": 13.0, "fat_g": 3.4, "carb_g": 41.0, "fibre_g": 7.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'high_fibre']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'bread_whole_wheat'),
  ('Oats, rolled', 'Jai', 'cereal_millet',
   '{"kcal": 389, "protein_g": 16.9, "fat_g": 6.9, "carb_g": 66.3, "fibre_g": 10.6, "iron_mg": 4.7, "magnesium_mg": 177}'::jsonb,
   array['veg', 'vegan', 'jain', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'oats_rolled'),
  ('Finger millet (ragi)', 'Ragi / Nachni', 'cereal_millet',
   '{"kcal": 328, "protein_g": 7.3, "fat_g": 1.3, "carb_g": 72.0, "fibre_g": 11.5, "calcium_mg": 344, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'ragi'),
  ('Pearl millet (bajra)', 'Bajra', 'cereal_millet',
   '{"kcal": 361, "protein_g": 11.6, "fat_g": 5.0, "carb_g": 67.5, "fibre_g": 11.5, "iron_mg": 8.0, "magnesium_mg": 137}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'bajra'),
  ('Sorghum (jowar)', 'Jowar', 'cereal_millet',
   '{"kcal": 349, "protein_g": 10.4, "fat_g": 1.9, "carb_g": 72.6, "fibre_g": 9.7, "iron_mg": 4.1}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'jowar'),
  ('Foxtail millet', 'Kangni / Korralu', 'cereal_millet',
   '{"kcal": 331, "protein_g": 12.3, "fat_g": 4.3, "carb_g": 60.9, "fibre_g": 8.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'foxtail_millet'),
  ('Little millet', 'Kutki / Samai', 'cereal_millet',
   '{"kcal": 346, "protein_g": 8.9, "fat_g": 3.9, "carb_g": 65.5, "fibre_g": 7.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'little_millet'),
  ('Barnyard millet', 'Sanwa / Udalu', 'cereal_millet',
   '{"kcal": 342, "protein_g": 6.2, "fat_g": 2.2, "carb_g": 65.5, "fibre_g": 8.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'barnyard_millet'),
  ('Kodo millet', 'Kodra / Arikelu', 'cereal_millet',
   '{"kcal": 331, "protein_g": 8.9, "fat_g": 2.6, "carb_g": 66.2, "fibre_g": 6.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'kodo_millet'),
  ('Quinoa, raw', 'Quinoa', 'cereal_millet',
   '{"kcal": 368, "protein_g": 14.1, "fat_g": 6.1, "carb_g": 64.2, "fibre_g": 7.0, "iron_mg": 4.6, "magnesium_mg": 197}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'quinoa'),
  ('Maize, dry (corn)', 'Makka', 'cereal_millet',
   '{"kcal": 342, "protein_g": 11.1, "fat_g": 3.6, "carb_g": 66.2, "fibre_g": 12.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'maize_dry'),
  ('Vermicelli (semiya)', 'Semiya', 'cereal_millet',
   '{"kcal": 352, "protein_g": 10.0, "fat_g": 1.0, "carb_g": 77.0, "fibre_g": 2.5}'::jsonb,
   array['veg', 'vegan', 'jain']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'vermicelli'),
  ('Broken wheat (dalia)', 'Dalia', 'cereal_millet',
   '{"kcal": 342, "protein_g": 12.0, "fat_g": 1.5, "carb_g": 69.0, "fibre_g": 9.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'high_fibre']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'dalia'),
  ('Sago pearls (sabudana)', 'Sabudana', 'cereal_millet',
   '{"kcal": 351, "protein_g": 0.2, "fat_g": 0.1, "carb_g": 87.0, "fibre_g": 0.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sabudana'),
  ('Idli rice, parboiled', 'Idli arisi', 'cereal_millet',
   '{"kcal": 346, "protein_g": 6.5, "fat_g": 0.6, "carb_g": 78.0, "fibre_g": 0.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'idli_rice'),
  -- pulse_legume
  ('Pigeon pea, split (toor / arhar dal)', 'Toor dal', 'pulse_legume',
   '{"kcal": 343, "protein_g": 22.3, "fat_g": 1.7, "carb_g": 57.6, "fibre_g": 15.0, "folate_ug": 456, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'toor_dal'),
  ('Green gram, split (moong dal)', 'Moong dal', 'pulse_legume',
   '{"kcal": 348, "protein_g": 24.5, "fat_g": 1.2, "carb_g": 59.9, "fibre_g": 16.3, "folate_ug": 625, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'moong_dal'),
  ('Green gram, whole', 'Sabut moong', 'pulse_legume',
   '{"kcal": 334, "protein_g": 24.0, "fat_g": 1.2, "carb_g": 56.7, "fibre_g": 16.3, "iron_mg": 6.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'moong_whole'),
  ('Red lentil, split (masoor dal)', 'Masoor dal', 'pulse_legume',
   '{"kcal": 343, "protein_g": 25.1, "fat_g": 1.1, "carb_g": 59.0, "fibre_g": 10.8, "folate_ug": 479, "iron_mg": 7.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'masoor_dal'),
  ('Bengal gram, split (chana dal)', 'Chana dal', 'pulse_legume',
   '{"kcal": 360, "protein_g": 21.0, "fat_g": 5.3, "carb_g": 57.0, "fibre_g": 12.0, "iron_mg": 5.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'chana_dal'),
  ('Chickpea, white (kabuli chana)', 'Kabuli chana', 'pulse_legume',
   '{"kcal": 364, "protein_g": 19.3, "fat_g": 6.0, "carb_g": 61.0, "fibre_g": 17.0, "folate_ug": 557, "iron_mg": 6.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'kabuli_chana'),
  ('Bengal gram, whole (kala chana)', 'Kala chana', 'pulse_legume',
   '{"kcal": 360, "protein_g": 20.0, "fat_g": 5.6, "carb_g": 58.0, "fibre_g": 17.0, "iron_mg": 5.8}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'kala_chana'),
  ('Kidney bean (rajma)', 'Rajma', 'pulse_legume',
   '{"kcal": 333, "protein_g": 23.6, "fat_g": 1.1, "carb_g": 60.0, "fibre_g": 15.2, "folate_ug": 394, "iron_mg": 8.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'rajma'),
  ('Black gram, split (urad dal)', 'Urad dal', 'pulse_legume',
   '{"kcal": 341, "protein_g": 24.0, "fat_g": 1.4, "carb_g": 59.0, "fibre_g": 13.0, "iron_mg": 7.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'urad_dal'),
  ('Cowpea (lobia / chawli)', 'Lobia', 'pulse_legume',
   '{"kcal": 343, "protein_g": 23.5, "fat_g": 1.3, "carb_g": 60.0, "fibre_g": 11.0, "iron_mg": 8.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'lobia'),
  ('Horse gram (kulthi)', 'Kulthi / Ulavalu', 'pulse_legume',
   '{"kcal": 321, "protein_g": 22.0, "fat_g": 0.5, "carb_g": 57.0, "fibre_g": 5.3, "iron_mg": 6.8}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'horse_gram'),
  ('Soyabean, dry', 'Soya', 'pulse_legume',
   '{"kcal": 432, "protein_g": 35.0, "fat_g": 19.9, "carb_g": 20.9, "fibre_g": 13.0, "calcium_mg": 277, "iron_mg": 15.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron', 'high_calcium']::text[], array['soy']::text[], 'india', 'PROVISIONAL', 'soyabean'),
  ('Dried green peas', 'Sukha matar', 'pulse_legume',
   '{"kcal": 341, "protein_g": 24.5, "fat_g": 1.2, "carb_g": 60.0, "fibre_g": 25.0, "iron_mg": 4.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'dried_peas'),
  ('Bengal gram flour (besan)', 'Besan', 'pulse_legume',
   '{"kcal": 387, "protein_g": 22.4, "fat_g": 6.7, "carb_g": 57.8, "fibre_g": 10.8, "folate_ug": 437, "iron_mg": 4.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'besan'),
  ('Green gram, sprouted', 'Ankurit moong', 'pulse_legume',
   '{"kcal": 30, "protein_g": 3.0, "fat_g": 0.2, "carb_g": 5.9, "fibre_g": 1.8, "vitamin_c_mg": 13.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sprouted_moong'),
  ('Moth bean (matki)', 'Matki', 'pulse_legume',
   '{"kcal": 343, "protein_g": 22.9, "fat_g": 1.6, "carb_g": 61.5, "fibre_g": 10.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'moth_bean'),
  -- nut_seed
  ('Almond', 'Badam', 'nut_seed',
   '{"kcal": 597, "protein_g": 20.8, "fat_g": 58.9, "carb_g": 10.5, "fibre_g": 12.5, "calcium_mg": 230, "iron_mg": 3.7, "magnesium_mg": 270}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron', 'high_calcium']::text[], array['tree_nut']::text[], 'india', 'PROVISIONAL', 'almond'),
  ('Cashew nut', 'Kaju', 'nut_seed',
   '{"kcal": 553, "protein_g": 18.2, "fat_g": 43.9, "carb_g": 30.2, "fibre_g": 3.3, "iron_mg": 6.7, "magnesium_mg": 292}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_iron']::text[], array['tree_nut']::text[], 'india', 'PROVISIONAL', 'cashew'),
  ('Walnut', 'Akhrot', 'nut_seed',
   '{"kcal": 654, "protein_g": 15.2, "fat_g": 65.2, "carb_g": 13.7, "fibre_g": 6.7, "magnesium_mg": 158}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], array['tree_nut']::text[], 'india', 'PROVISIONAL', 'walnut'),
  ('Groundnut', 'Moongphali', 'nut_seed',
   '{"kcal": 567, "protein_g": 25.8, "fat_g": 49.2, "carb_g": 16.1, "fibre_g": 8.5, "folate_ug": 240, "magnesium_mg": 168}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], array['peanut']::text[], 'india', 'PROVISIONAL', 'peanut'),
  ('Pistachio', 'Pista', 'nut_seed',
   '{"kcal": 560, "protein_g": 20.2, "fat_g": 45.3, "carb_g": 27.2, "fibre_g": 10.6, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], array['tree_nut']::text[], 'india', 'PROVISIONAL', 'pistachio'),
  ('Sesame seed', 'Til', 'nut_seed',
   '{"kcal": 573, "protein_g": 17.7, "fat_g": 49.7, "carb_g": 23.4, "fibre_g": 11.8, "calcium_mg": 975, "iron_mg": 14.6, "magnesium_mg": 351}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron', 'high_calcium']::text[], array['sesame']::text[], 'india', 'PROVISIONAL', 'sesame_seed'),
  ('Flax seed', 'Alsi', 'nut_seed',
   '{"kcal": 534, "protein_g": 18.3, "fat_g": 42.2, "carb_g": 28.9, "fibre_g": 27.3, "magnesium_mg": 392}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'flax_seed'),
  ('Chia seed', 'Chia', 'nut_seed',
   '{"kcal": 486, "protein_g": 16.5, "fat_g": 30.7, "carb_g": 42.1, "fibre_g": 34.4, "calcium_mg": 631, "iron_mg": 7.7, "magnesium_mg": 335}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'chia_seed'),
  ('Sunflower seed', 'Surajmukhi beej', 'nut_seed',
   '{"kcal": 584, "protein_g": 20.8, "fat_g": 51.5, "carb_g": 20.0, "fibre_g": 8.6, "magnesium_mg": 325}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'sunflower_seed'),
  ('Pumpkin seed', 'Kaddu ke beej', 'nut_seed',
   '{"kcal": 559, "protein_g": 30.2, "fat_g": 49.1, "carb_g": 10.7, "fibre_g": 6.0, "iron_mg": 8.8, "magnesium_mg": 592, "zinc_mg": 7.8}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'pumpkin_seed'),
  ('Coconut, fresh kernel', 'Nariyal', 'nut_seed',
   '{"kcal": 354, "protein_g": 3.3, "fat_g": 33.5, "carb_g": 15.2, "fibre_g": 9.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'coconut_fresh'),
  ('Coconut, dry (copra)', 'Khopra', 'nut_seed',
   '{"kcal": 660, "protein_g": 6.9, "fat_g": 62.0, "carb_g": 25.0, "fibre_g": 16.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'coconut_dry'),
  -- vegetable
  ('Potato', 'Aloo', 'vegetable',
   '{"kcal": 77, "protein_g": 2.0, "fat_g": 0.1, "carb_g": 17.5, "fibre_g": 2.1, "potassium_mg": 425, "vitamin_c_mg": 19.7}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'potato'),
  ('Sweet potato', 'Shakarkandi', 'vegetable',
   '{"kcal": 86, "protein_g": 1.6, "fat_g": 0.1, "carb_g": 20.1, "fibre_g": 3.0, "vitamin_a_ug": 709}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sweet_potato'),
  ('Onion', 'Pyaz', 'vegetable',
   '{"kcal": 40, "protein_g": 1.1, "fat_g": 0.1, "carb_g": 9.3, "fibre_g": 1.7}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'onion'),
  ('Tomato, ripe', 'Tamatar', 'vegetable',
   '{"kcal": 18, "protein_g": 0.9, "fat_g": 0.2, "carb_g": 3.9, "fibre_g": 1.2, "vitamin_c_mg": 13.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'tomato'),
  ('Brinjal (aubergine)', 'Baingan', 'vegetable',
   '{"kcal": 25, "protein_g": 1.0, "fat_g": 0.2, "carb_g": 5.9, "fibre_g": 3.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'brinjal'),
  ('Okra (ladies finger)', 'Bhindi', 'vegetable',
   '{"kcal": 33, "protein_g": 1.9, "fat_g": 0.2, "carb_g": 7.5, "fibre_g": 3.2, "calcium_mg": 82, "folate_ug": 60}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'okra'),
  ('Bottle gourd', 'Lauki / Sorakaya', 'vegetable',
   '{"kcal": 14, "protein_g": 0.6, "fat_g": 0.1, "carb_g": 3.4, "fibre_g": 0.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'bottle_gourd'),
  ('Ridge gourd', 'Turai / Beerakaya', 'vegetable',
   '{"kcal": 20, "protein_g": 1.2, "fat_g": 0.2, "carb_g": 4.4, "fibre_g": 1.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'ridge_gourd'),
  ('Bitter gourd', 'Karela / Kakarakaya', 'vegetable',
   '{"kcal": 17, "protein_g": 1.0, "fat_g": 0.2, "carb_g": 3.7, "fibre_g": 2.8, "vitamin_c_mg": 84}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'bitter_gourd'),
  ('Pumpkin', 'Kaddu / Gummadikaya', 'vegetable',
   '{"kcal": 26, "protein_g": 1.0, "fat_g": 0.1, "carb_g": 6.5, "fibre_g": 0.5, "vitamin_a_ug": 426}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'pumpkin'),
  ('Cauliflower', 'Phool gobhi', 'vegetable',
   '{"kcal": 25, "protein_g": 1.9, "fat_g": 0.3, "carb_g": 5.0, "fibre_g": 2.0, "vitamin_c_mg": 48}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'cauliflower'),
  ('Cabbage', 'Patta gobhi', 'vegetable',
   '{"kcal": 25, "protein_g": 1.3, "fat_g": 0.1, "carb_g": 5.8, "fibre_g": 2.5, "vitamin_c_mg": 36}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'cabbage'),
  ('Carrot', 'Gajar', 'vegetable',
   '{"kcal": 41, "protein_g": 0.9, "fat_g": 0.2, "carb_g": 9.6, "fibre_g": 2.8, "vitamin_a_ug": 835}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'carrot'),
  ('Beetroot', 'Chukandar', 'vegetable',
   '{"kcal": 43, "protein_g": 1.6, "fat_g": 0.2, "carb_g": 9.6, "fibre_g": 2.8, "folate_ug": 109}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'beetroot'),
  ('Radish', 'Mooli', 'vegetable',
   '{"kcal": 16, "protein_g": 0.7, "fat_g": 0.1, "carb_g": 3.4, "fibre_g": 1.6}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'radish'),
  ('Capsicum, green', 'Shimla mirch', 'vegetable',
   '{"kcal": 20, "protein_g": 0.9, "fat_g": 0.2, "carb_g": 4.6, "fibre_g": 1.7, "vitamin_c_mg": 80}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'capsicum_green'),
  ('French beans', 'Farasbi', 'vegetable',
   '{"kcal": 31, "protein_g": 1.8, "fat_g": 0.1, "carb_g": 7.0, "fibre_g": 2.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'french_beans'),
  ('Cluster beans', 'Gawar / Goru chikkudu', 'vegetable',
   '{"kcal": 46, "protein_g": 3.2, "fat_g": 0.4, "carb_g": 10.8, "fibre_g": 3.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'cluster_beans'),
  ('Drumstick, pod', 'Sahjan / Munagakaya', 'vegetable',
   '{"kcal": 37, "protein_g": 2.1, "fat_g": 0.2, "carb_g": 8.5, "fibre_g": 3.2, "vitamin_c_mg": 141}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'drumstick_pod'),
  ('Mushroom, button', 'Khumb', 'vegetable',
   '{"kcal": 22, "protein_g": 3.1, "fat_g": 0.3, "carb_g": 3.3, "fibre_g": 1.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'mushroom_button'),
  ('Cucumber', 'Kheera', 'vegetable',
   '{"kcal": 15, "protein_g": 0.7, "fat_g": 0.1, "carb_g": 3.6, "fibre_g": 0.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'cucumber'),
  ('Ash gourd', 'Petha / Boodida gummadi', 'vegetable',
   '{"kcal": 13, "protein_g": 0.4, "fat_g": 0.2, "carb_g": 3.0, "fibre_g": 2.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'ash_gourd'),
  ('Colocasia root', 'Arbi / Chamagadda', 'vegetable',
   '{"kcal": 112, "protein_g": 1.5, "fat_g": 0.2, "carb_g": 26.5, "fibre_g": 4.1}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'colocasia'),
  ('Elephant foot yam', 'Suran / Kanda', 'vegetable',
   '{"kcal": 118, "protein_g": 1.5, "fat_g": 0.2, "carb_g": 27.9, "fibre_g": 4.1}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'elephant_yam'),
  ('Green peas, fresh', 'Hara matar', 'vegetable',
   '{"kcal": 81, "protein_g": 5.4, "fat_g": 0.4, "carb_g": 14.5, "fibre_g": 5.1, "folate_ug": 65, "vitamin_c_mg": 40}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'green_peas_fresh'),
  ('Sweet corn, fresh', 'Bhutta', 'vegetable',
   '{"kcal": 86, "protein_g": 3.3, "fat_g": 1.4, "carb_g": 19.0, "fibre_g": 2.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sweet_corn'),
  ('Broccoli', 'Broccoli', 'vegetable',
   '{"kcal": 34, "protein_g": 2.8, "fat_g": 0.4, "carb_g": 6.6, "fibre_g": 2.6, "folate_ug": 63, "vitamin_c_mg": 89}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'broccoli'),
  ('Ivy gourd', 'Tindora / Dondakaya', 'vegetable',
   '{"kcal": 18, "protein_g": 1.2, "fat_g": 0.1, "carb_g": 3.1, "fibre_g": 1.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'ivy_gourd'),
  ('Snake gourd', 'Chichinda / Potlakaya', 'vegetable',
   '{"kcal": 18, "protein_g": 0.5, "fat_g": 0.3, "carb_g": 3.3, "fibre_g": 0.8}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'snake_gourd'),
  ('Plantain, green (raw banana)', 'Kachcha kela / Aratikaya', 'vegetable',
   '{"kcal": 122, "protein_g": 1.3, "fat_g": 0.4, "carb_g": 31.9, "fibre_g": 2.3}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'raw_plantain'),
  ('Garlic', 'Lehsun', 'vegetable',
   '{"kcal": 149, "protein_g": 6.4, "fat_g": 0.5, "carb_g": 33.1, "fibre_g": 2.1}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'garlic'),
  ('Ginger, fresh', 'Adrak', 'vegetable',
   '{"kcal": 80, "protein_g": 1.8, "fat_g": 0.8, "carb_g": 17.8, "fibre_g": 2.0}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'ginger'),
  ('Green chilli', 'Hari mirch', 'vegetable',
   '{"kcal": 40, "protein_g": 1.9, "fat_g": 0.4, "carb_g": 8.8, "fibre_g": 1.5, "vitamin_c_mg": 143}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'green_chilli'),
  -- leafy_vegetable
  ('Spinach', 'Palak', 'leafy_vegetable',
   '{"kcal": 23, "protein_g": 2.9, "fat_g": 0.4, "carb_g": 3.6, "fibre_g": 2.2, "calcium_mg": 99, "folate_ug": 194, "iron_mg": 2.7, "vitamin_a_ug": 469}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'spinach'),
  ('Amaranth leaves', 'Chaulai / Thotakura', 'leafy_vegetable',
   '{"kcal": 23, "protein_g": 2.5, "fat_g": 0.3, "carb_g": 4.0, "fibre_g": 2.2, "calcium_mg": 215, "iron_mg": 2.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'amaranth_leaves'),
  ('Fenugreek leaves', 'Methi / Menthikura', 'leafy_vegetable',
   '{"kcal": 49, "protein_g": 4.4, "fat_g": 0.9, "carb_g": 6.0, "fibre_g": 1.1, "calcium_mg": 395, "iron_mg": 1.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'fenugreek_leaves'),
  ('Coriander leaves', 'Dhania / Kothimeera', 'leafy_vegetable',
   '{"kcal": 23, "protein_g": 2.1, "fat_g": 0.5, "carb_g": 3.7, "fibre_g": 2.8, "vitamin_c_mg": 27}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'coriander_leaves'),
  ('Curry leaves', 'Kadi patta / Karivepaku', 'leafy_vegetable',
   '{"kcal": 108, "protein_g": 6.1, "fat_g": 1.0, "carb_g": 18.7, "fibre_g": 6.4, "calcium_mg": 830, "iron_mg": 0.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'curry_leaves'),
  ('Mint leaves', 'Pudina', 'leafy_vegetable',
   '{"kcal": 44, "protein_g": 3.3, "fat_g": 0.7, "carb_g": 8.4, "fibre_g": 6.8, "iron_mg": 5.1}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'mint_leaves'),
  ('Mustard leaves', 'Sarson ka saag', 'leafy_vegetable',
   '{"kcal": 27, "protein_g": 2.9, "fat_g": 0.4, "carb_g": 4.7, "fibre_g": 3.2, "vitamin_c_mg": 70}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], array['mustard']::text[], 'india', 'PROVISIONAL', 'mustard_leaves'),
  ('Drumstick (moringa) leaves', 'Munagaku', 'leafy_vegetable',
   '{"kcal": 64, "protein_g": 9.4, "fat_g": 1.4, "carb_g": 8.3, "fibre_g": 2.0, "calcium_mg": 185, "iron_mg": 4.0, "vitamin_c_mg": 51}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_iron', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'drumstick_leaves'),
  -- fruit
  ('Banana', 'Kela', 'fruit',
   '{"kcal": 89, "protein_g": 1.1, "fat_g": 0.3, "carb_g": 22.8, "fibre_g": 2.6, "potassium_mg": 358}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'banana'),
  ('Apple, with skin', 'Seb', 'fruit',
   '{"kcal": 52, "protein_g": 0.3, "fat_g": 0.2, "carb_g": 13.8, "fibre_g": 2.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'apple'),
  ('Mango, ripe', 'Aam', 'fruit',
   '{"kcal": 60, "protein_g": 0.8, "fat_g": 0.4, "carb_g": 15.0, "fibre_g": 1.6, "vitamin_a_ug": 54, "vitamin_c_mg": 36}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'mango'),
  ('Papaya, ripe', 'Papita', 'fruit',
   '{"kcal": 43, "protein_g": 0.5, "fat_g": 0.3, "carb_g": 10.8, "fibre_g": 1.7, "vitamin_c_mg": 61}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'papaya'),
  ('Guava', 'Amrud / Jamakaya', 'fruit',
   '{"kcal": 68, "protein_g": 2.6, "fat_g": 0.9, "carb_g": 14.3, "fibre_g": 5.4, "vitamin_c_mg": 228}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'guava'),
  ('Orange', 'Santra', 'fruit',
   '{"kcal": 47, "protein_g": 0.9, "fat_g": 0.1, "carb_g": 11.8, "fibre_g": 2.4, "folate_ug": 30, "vitamin_c_mg": 53}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'orange'),
  ('Sweet lime', 'Mosambi', 'fruit',
   '{"kcal": 43, "protein_g": 0.8, "fat_g": 0.3, "carb_g": 9.3, "fibre_g": 0.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sweet_lime'),
  ('Grapes', 'Angoor', 'fruit',
   '{"kcal": 69, "protein_g": 0.7, "fat_g": 0.2, "carb_g": 18.1, "fibre_g": 0.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'grapes'),
  ('Pomegranate', 'Anar', 'fruit',
   '{"kcal": 83, "protein_g": 1.7, "fat_g": 1.2, "carb_g": 18.7, "fibre_g": 4.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'pomegranate'),
  ('Watermelon', 'Tarbooz', 'fruit',
   '{"kcal": 30, "protein_g": 0.6, "fat_g": 0.2, "carb_g": 7.6, "fibre_g": 0.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'watermelon'),
  ('Muskmelon', 'Kharbooja', 'fruit',
   '{"kcal": 34, "protein_g": 0.8, "fat_g": 0.2, "carb_g": 8.2, "fibre_g": 0.9, "vitamin_c_mg": 37}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'muskmelon'),
  ('Pineapple', 'Ananas', 'fruit',
   '{"kcal": 50, "protein_g": 0.5, "fat_g": 0.1, "carb_g": 13.1, "fibre_g": 1.4, "vitamin_c_mg": 48}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'pineapple'),
  ('Sapota (chikoo)', 'Chikoo', 'fruit',
   '{"kcal": 83, "protein_g": 0.4, "fat_g": 1.1, "carb_g": 20.0, "fibre_g": 5.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sapota'),
  ('Custard apple', 'Sitaphal', 'fruit',
   '{"kcal": 94, "protein_g": 2.1, "fat_g": 0.3, "carb_g": 23.6, "fibre_g": 4.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'custard_apple'),
  ('Jackfruit, ripe', 'Kathal / Panasa', 'fruit',
   '{"kcal": 95, "protein_g": 1.7, "fat_g": 0.6, "carb_g": 23.2, "fibre_g": 1.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'jackfruit'),
  ('Pear', 'Nashpati', 'fruit',
   '{"kcal": 57, "protein_g": 0.4, "fat_g": 0.1, "carb_g": 15.2, "fibre_g": 3.1}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'pear'),
  ('Plum', 'Aloo bukhara', 'fruit',
   '{"kcal": 46, "protein_g": 0.7, "fat_g": 0.3, "carb_g": 11.4, "fibre_g": 1.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'plum'),
  ('Litchi', 'Litchi', 'fruit',
   '{"kcal": 66, "protein_g": 0.8, "fat_g": 0.4, "carb_g": 16.5, "fibre_g": 1.3, "vitamin_c_mg": 72}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'litchi'),
  ('Strawberry', 'Strawberry', 'fruit',
   '{"kcal": 32, "protein_g": 0.7, "fat_g": 0.3, "carb_g": 7.7, "fibre_g": 2.0, "vitamin_c_mg": 59}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'strawberry'),
  ('Dates, dried', 'Khajoor', 'fruit',
   '{"kcal": 282, "protein_g": 2.5, "fat_g": 0.4, "carb_g": 75.0, "fibre_g": 8.0, "iron_mg": 1.0, "potassium_mg": 656}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'dates_dry'),
  ('Raisins', 'Kishmish', 'fruit',
   '{"kcal": 299, "protein_g": 3.1, "fat_g": 0.5, "carb_g": 79.2, "fibre_g": 3.7, "iron_mg": 1.9, "potassium_mg": 749}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'raisins'),
  ('Fig, dried', 'Anjeer', 'fruit',
   '{"kcal": 249, "protein_g": 3.3, "fat_g": 0.9, "carb_g": 63.9, "fibre_g": 9.8, "calcium_mg": 162, "iron_mg": 2.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'fig_dry'),
  ('Indian gooseberry', 'Amla / Usirikaya', 'fruit',
   '{"kcal": 44, "protein_g": 0.9, "fat_g": 0.6, "carb_g": 10.2, "fibre_g": 4.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'amla'),
  ('Lemon', 'Nimbu', 'fruit',
   '{"kcal": 29, "protein_g": 1.1, "fat_g": 0.3, "carb_g": 9.3, "fibre_g": 2.8, "vitamin_c_mg": 53}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'lemon'),
  -- dairy
  ('Cow milk, whole', 'Gaay ka doodh', 'dairy',
   '{"kcal": 61, "protein_g": 3.2, "fat_g": 3.3, "carb_g": 4.8, "fibre_g": 0.0, "b12_ug": 0.4, "calcium_mg": 120}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'cow_milk_whole'),
  ('Buffalo milk', 'Bhains ka doodh', 'dairy',
   '{"kcal": 97, "protein_g": 3.8, "fat_g": 6.9, "carb_g": 5.2, "fibre_g": 0.0, "calcium_mg": 169}'::jsonb,
   array['veg', 'gluten_free', 'high_calcium']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'buffalo_milk'),
  ('Toned milk', 'Toned doodh', 'dairy',
   '{"kcal": 58, "protein_g": 3.1, "fat_g": 3.0, "carb_g": 4.7, "fibre_g": 0.0, "calcium_mg": 120}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'toned_milk'),
  ('Skimmed milk', 'Skimmed doodh', 'dairy',
   '{"kcal": 35, "protein_g": 3.4, "fat_g": 0.1, "carb_g": 5.0, "fibre_g": 0.0, "b12_ug": 0.5, "calcium_mg": 122}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'skimmed_milk'),
  ('Curd (dahi), whole milk', 'Dahi / Perugu', 'dairy',
   '{"kcal": 60, "protein_g": 3.5, "fat_g": 3.3, "carb_g": 4.7, "fibre_g": 0.0, "b12_ug": 0.4, "calcium_mg": 120}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'curd_whole'),
  ('Paneer', 'Paneer', 'dairy',
   '{"kcal": 265, "protein_g": 18.3, "fat_g": 20.8, "carb_g": 1.2, "fibre_g": 0.0, "calcium_mg": 208}'::jsonb,
   array['veg', 'gluten_free', 'high_protein', 'high_calcium']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'paneer'),
  ('Cheese, processed', 'Cheese', 'dairy',
   '{"kcal": 350, "protein_g": 22.0, "fat_g": 28.0, "carb_g": 2.0, "fibre_g": 0.0, "calcium_mg": 700}'::jsonb,
   array['veg', 'gluten_free', 'high_protein', 'high_calcium']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'cheese_processed'),
  ('Butter', 'Makkhan', 'dairy',
   '{"kcal": 717, "protein_g": 0.9, "fat_g": 81.1, "carb_g": 0.1, "fibre_g": 0.0}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'butter'),
  ('Ghee', 'Ghee', 'dairy',
   '{"kcal": 900, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'ghee'),
  ('Khoa (mawa)', 'Khoya', 'dairy',
   '{"kcal": 421, "protein_g": 14.6, "fat_g": 31.2, "carb_g": 20.5, "fibre_g": 0.0, "calcium_mg": 650}'::jsonb,
   array['veg', 'gluten_free', 'high_calcium']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'khoa'),
  ('Buttermilk (chaas)', 'Chaas / Majjiga', 'dairy',
   '{"kcal": 40, "protein_g": 3.3, "fat_g": 0.9, "carb_g": 4.8, "fibre_g": 0.0, "calcium_mg": 116}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'buttermilk'),
  -- egg
  ('Egg, hen, whole', 'Anda', 'egg',
   '{"kcal": 155, "protein_g": 12.6, "fat_g": 10.6, "carb_g": 1.1, "fibre_g": 0.0, "b12_ug": 1.1, "vitamin_d_ug": 2.0}'::jsonb,
   array['egg', 'gluten_free']::text[], array['egg']::text[], 'india', 'PROVISIONAL', 'egg_whole'),
  ('Egg white', 'Ande ka safed bhag', 'egg',
   '{"kcal": 52, "protein_g": 10.9, "fat_g": 0.2, "carb_g": 0.7, "fibre_g": 0.0}'::jsonb,
   array['egg', 'gluten_free']::text[], array['egg']::text[], 'india', 'PROVISIONAL', 'egg_white'),
  ('Egg yolk', 'Ande ki zardi', 'egg',
   '{"kcal": 322, "protein_g": 15.9, "fat_g": 26.5, "carb_g": 3.6, "fibre_g": 0.0, "b12_ug": 1.9, "vitamin_d_ug": 5.4}'::jsonb,
   array['egg', 'gluten_free', 'high_protein']::text[], array['egg']::text[], 'india', 'PROVISIONAL', 'egg_yolk'),
  -- meat_poultry
  ('Chicken breast, skinless', 'Murgi ka seena', 'meat_poultry',
   '{"kcal": 165, "protein_g": 31.0, "fat_g": 3.6, "carb_g": 0.0, "fibre_g": 0.0, "b12_ug": 0.3}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], '{}', 'india', 'PROVISIONAL', 'chicken_breast'),
  ('Chicken, whole with skin', 'Murgi', 'meat_poultry',
   '{"kcal": 215, "protein_g": 18.6, "fat_g": 15.1, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], '{}', 'india', 'PROVISIONAL', 'chicken_whole'),
  ('Goat meat (mutton)', 'Bakra gosht', 'meat_poultry',
   '{"kcal": 143, "protein_g": 27.1, "fat_g": 3.0, "carb_g": 0.0, "fibre_g": 0.0, "b12_ug": 1.2, "iron_mg": 3.7, "zinc_mg": 4.5}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'goat_mutton'),
  ('Goat liver', 'Kaleji', 'meat_poultry',
   '{"kcal": 139, "protein_g": 20.4, "fat_g": 4.7, "carb_g": 2.6, "fibre_g": 0.0, "iron_mg": 6.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'goat_liver'),
  -- fish_seafood
  ('Rohu (fish)', 'Rohu', 'fish_seafood',
   '{"kcal": 97, "protein_g": 16.6, "fat_g": 1.4, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'rohu'),
  ('Pomfret (fish)', 'Paplet', 'fish_seafood',
   '{"kcal": 96, "protein_g": 20.0, "fat_g": 1.3, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'pomfret'),
  ('Seer fish (surmai)', 'Surmai / Vanjaram', 'fish_seafood',
   '{"kcal": 105, "protein_g": 21.0, "fat_g": 2.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'kingfish'),
  ('Sardine, canned in oil, drained', 'Sardine', 'fish_seafood',
   '{"kcal": 208, "protein_g": 24.6, "fat_g": 11.5, "carb_g": 0.0, "fibre_g": 0.0, "b12_ug": 8.9, "calcium_mg": 382, "vitamin_d_ug": 4.8}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein', 'high_calcium']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'sardine_canned'),
  ('Mackerel (bangda)', 'Bangda', 'fish_seafood',
   '{"kcal": 205, "protein_g": 18.6, "fat_g": 13.9, "carb_g": 0.0, "fibre_g": 0.0, "b12_ug": 8.7, "vitamin_d_ug": 16.1}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'mackerel'),
  ('Prawn', 'Jhinga / Royya', 'fish_seafood',
   '{"kcal": 99, "protein_g": 24.0, "fat_g": 0.3, "carb_g": 0.2, "fibre_g": 0.0, "b12_ug": 1.1}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['shellfish']::text[], 'india', 'PROVISIONAL', 'prawn'),
  -- oil_fat
  ('Groundnut oil', 'Moongphali ka tel', 'oil_fat',
   '{"kcal": 884, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], array['peanut']::text[], 'india', 'PROVISIONAL', 'groundnut_oil'),
  ('Mustard oil', 'Sarson ka tel', 'oil_fat',
   '{"kcal": 884, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], array['mustard']::text[], 'india', 'PROVISIONAL', 'mustard_oil'),
  ('Coconut oil', 'Nariyal tel', 'oil_fat',
   '{"kcal": 862, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'coconut_oil'),
  ('Sunflower oil', 'Surajmukhi tel', 'oil_fat',
   '{"kcal": 884, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sunflower_oil'),
  ('Sesame oil (gingelly)', 'Til ka tel', 'oil_fat',
   '{"kcal": 884, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], array['sesame']::text[], 'india', 'PROVISIONAL', 'sesame_oil'),
  -- sugar_sweetener
  ('Sugar, white', 'Cheeni', 'sugar_sweetener',
   '{"kcal": 387, "protein_g": 0.0, "fat_g": 0.0, "carb_g": 99.8, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sugar'),
  ('Jaggery', 'Gud / Bellam', 'sugar_sweetener',
   '{"kcal": 383, "protein_g": 0.4, "fat_g": 0.1, "carb_g": 97.0, "fibre_g": 0.0, "iron_mg": 2.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'jaggery'),
  ('Honey', 'Shahad', 'sugar_sweetener',
   '{"kcal": 304, "protein_g": 0.3, "fat_g": 0.0, "carb_g": 82.4, "fibre_g": 0.2}'::jsonb,
   array['veg', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'honey')
on conflict (source, source_id) do nothing;


-- ============================================================================
-- CHECKS
-- ============================================================================

-- 1. How many foods loaded, and how many are still provisional.
select count(*) as foods_loaded,
       count(*) filter (where source = 'PROVISIONAL') as still_provisional
from public.foods;

-- 2. Foods by group.
select food_group, count(*) as n
from public.foods
group by food_group
order by food_group;

-- 3. Every food must have the five core nutrients. This must return 0 rows.
select name
from public.foods
where not (per_100g ?& array['kcal', 'protein_g', 'fat_g', 'carb_g', 'fibre_g']);

-- 4. Example of the candidate list the planner asks for: vegetarian,
--    high-iron, no peanut allergy.
select name, per_100g ->> 'iron_mg' as iron_mg
from public.foods
where diet_flags @> array['veg']::text[]
  and diet_flags @> array['high_iron']::text[]
  and not (allergens && array['peanut']::text[])
order by (per_100g ->> 'iron_mg')::numeric desc;
