-- ============================================================================
-- 204_foods_starter.sql
-- HealthPulse seed - starter food composition table
--
-- Run AFTER the migrations. Safe to run more than once.
--
-- 147 common Indian foods, per 100 g of edible portion, raw unless the name says
-- otherwise.
--
-- ###########################################################################
-- #  READ THIS BEFORE YOU TRUST A NUMBER IN THIS FILE                       #
-- #                                                                         #
-- #  Every row is loaded with  source = 'PROVISIONAL'.                      #
-- #                                                                         #
-- #  That is deliberate and it is not a placeholder to be quietly deleted.  #
-- #  These values are typical published composition figures for each food.  #
-- #  They have NOT been checked line by line against IFCT 2017 or USDA      #
-- #  FoodData Central, and they carry no IFCT or USDA record number.        #
-- #  Claiming source = 'IFCT2017' without that check would be inventing a   #
-- #  provenance, which is exactly what CLAUDE.md forbids.                   #
-- #                                                                         #
-- #  They are good enough to build and test the planner against. Before any #
-- #  real user is shown a nutrient number, run a verified import and flip   #
-- #  each row to source = 'IFCT2017' or 'USDA' with the real source_id.     #
-- #  db/seed/GAPS.md has the full list of what to check.                    #
-- ###########################################################################
--
-- WHAT IS AND IS NOT IN per_100g
--   Always present: kcal, protein_g, fat_g, carb_g, fibre_g.
--   Micronutrients (iron_mg, calcium_mg, folate_ug, b12_ug, vitamin_d_ug,
--   vitamin_a_ug, vitamin_c_mg, magnesium_mg, zinc_mg, potassium_mg) are
--   present ONLY where the food is a well-known source of that nutrient and the
--   figure is a widely published one.
--
--   A MISSING KEY MEANS "WE DO NOT KNOW", NOT "ZERO". The backend must treat an
--   absent key as unknown and must not add it into a daily total as 0.
--
-- diet_flags   veg, vegan, egg, non_veg, jain, gluten_free, high_protein,
--              high_fibre, high_iron, high_calcium
--              'jain' excludes root vegetables, onion, garlic, ginger and honey.
--              'gluten_free' is not claimed for oats (cross-contamination).
-- allergens    milk, egg, peanut, tree_nut, sesame, soy, fish, shellfish,
--              gluten, mustard.  This list is a HARD filter against the
--              allergies table - never a suggestion.
-- ============================================================================

insert into public.foods
  (name, name_local, food_group, per_100g, diet_flags, allergens, region, source, source_id)
values
  -- cereal_millet
  ('Rice, raw milled', 'Chawal', 'cereal_millet',
   '{"kcal": 345, "protein_g": 6.8, "fat_g": 0.5, "carb_g": 78.2, "fibre_g": 0.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'rice_raw_milled'),
  ('Rice, parboiled milled', 'Ukda chawal', 'cereal_millet',
   '{"kcal": 346, "protein_g": 6.5, "fat_g": 0.6, "carb_g": 78.0, "fibre_g": 0.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'rice_parboiled'),
  ('Rice, brown', 'Brown chawal', 'cereal_millet',
   '{"kcal": 362, "protein_g": 7.5, "fat_g": 2.7, "carb_g": 76.0, "fibre_g": 3.5, "magnesium_mg": 143}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'rice_brown'),
  ('Wheat flour, wholemeal (atta)', 'Gehun atta', 'cereal_millet',
   '{"kcal": 341, "protein_g": 12.1, "fat_g": 1.7, "carb_g": 69.4, "fibre_g": 11.0, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'high_fibre', 'high_iron']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'wheat_flour_atta'),
  ('Wheat flour, refined (maida)', 'Maida', 'cereal_millet',
   '{"kcal": 348, "protein_g": 10.4, "fat_g": 0.8, "carb_g": 74.0, "fibre_g": 2.7}'::jsonb,
   array['veg', 'vegan', 'jain']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'maida'),
  ('Semolina (rava / suji)', 'Rava', 'cereal_millet',
   '{"kcal": 348, "protein_g": 10.4, "fat_g": 1.0, "carb_g": 74.8, "fibre_g": 3.5}'::jsonb,
   array['veg', 'vegan', 'jain']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'semolina'),
  ('Rice flakes (poha)', 'Poha', 'cereal_millet',
   '{"kcal": 346, "protein_g": 6.6, "fat_g": 1.2, "carb_g": 77.3, "fibre_g": 2.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'poha'),
  ('Bread, wholemeal', 'Brown bread', 'cereal_millet',
   '{"kcal": 247, "protein_g": 13.0, "fat_g": 3.4, "carb_g": 41.0, "fibre_g": 7.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'high_fibre']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'bread_whole_wheat'),
  ('Oats, rolled', 'Jai', 'cereal_millet',
   '{"kcal": 389, "protein_g": 16.9, "fat_g": 6.9, "carb_g": 66.3, "fibre_g": 10.6, "iron_mg": 4.7, "magnesium_mg": 177}'::jsonb,
   array['veg', 'vegan', 'jain', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'oats_rolled'),
  ('Finger millet (ragi)', 'Ragi / Nachni', 'cereal_millet',
   '{"kcal": 328, "protein_g": 7.3, "fat_g": 1.3, "carb_g": 72.0, "fibre_g": 11.5, "calcium_mg": 344, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'ragi'),
  ('Pearl millet (bajra)', 'Bajra', 'cereal_millet',
   '{"kcal": 361, "protein_g": 11.6, "fat_g": 5.0, "carb_g": 67.5, "fibre_g": 11.5, "iron_mg": 8.0, "magnesium_mg": 137}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'bajra'),
  ('Sorghum (jowar)', 'Jowar', 'cereal_millet',
   '{"kcal": 349, "protein_g": 10.4, "fat_g": 1.9, "carb_g": 72.6, "fibre_g": 9.7, "iron_mg": 4.1}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'jowar'),
  ('Foxtail millet', 'Kangni / Korralu', 'cereal_millet',
   '{"kcal": 331, "protein_g": 12.3, "fat_g": 4.3, "carb_g": 60.9, "fibre_g": 8.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'foxtail_millet'),
  ('Little millet', 'Kutki / Samai', 'cereal_millet',
   '{"kcal": 346, "protein_g": 8.9, "fat_g": 3.9, "carb_g": 65.5, "fibre_g": 7.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'little_millet'),
  ('Barnyard millet', 'Sanwa / Udalu', 'cereal_millet',
   '{"kcal": 342, "protein_g": 6.2, "fat_g": 2.2, "carb_g": 65.5, "fibre_g": 8.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'barnyard_millet'),
  ('Kodo millet', 'Kodra / Arikelu', 'cereal_millet',
   '{"kcal": 331, "protein_g": 8.9, "fat_g": 2.6, "carb_g": 66.2, "fibre_g": 6.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'kodo_millet'),
  ('Quinoa, raw', 'Quinoa', 'cereal_millet',
   '{"kcal": 368, "protein_g": 14.1, "fat_g": 6.1, "carb_g": 64.2, "fibre_g": 7.0, "iron_mg": 4.6, "magnesium_mg": 197}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'quinoa'),
  ('Maize, dry (corn)', 'Makka', 'cereal_millet',
   '{"kcal": 342, "protein_g": 11.1, "fat_g": 3.6, "carb_g": 66.2, "fibre_g": 12.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'maize_dry'),
  ('Vermicelli (semiya)', 'Semiya', 'cereal_millet',
   '{"kcal": 352, "protein_g": 10.0, "fat_g": 1.0, "carb_g": 77.0, "fibre_g": 2.5}'::jsonb,
   array['veg', 'vegan', 'jain']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'vermicelli'),
  ('Broken wheat (dalia)', 'Dalia', 'cereal_millet',
   '{"kcal": 342, "protein_g": 12.0, "fat_g": 1.5, "carb_g": 69.0, "fibre_g": 9.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'high_fibre']::text[], array['gluten']::text[], 'india', 'PROVISIONAL', 'dalia'),
  ('Sago pearls (sabudana)', 'Sabudana', 'cereal_millet',
   '{"kcal": 351, "protein_g": 0.2, "fat_g": 0.1, "carb_g": 87.0, "fibre_g": 0.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sabudana'),
  ('Idli rice, parboiled', 'Idli arisi', 'cereal_millet',
   '{"kcal": 346, "protein_g": 6.5, "fat_g": 0.6, "carb_g": 78.0, "fibre_g": 0.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'idli_rice'),
  -- pulse_legume
  ('Pigeon pea, split (toor / arhar dal)', 'Toor dal', 'pulse_legume',
   '{"kcal": 343, "protein_g": 22.3, "fat_g": 1.7, "carb_g": 57.6, "fibre_g": 15.0, "folate_ug": 456, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'toor_dal'),
  ('Green gram, split (moong dal)', 'Moong dal', 'pulse_legume',
   '{"kcal": 348, "protein_g": 24.5, "fat_g": 1.2, "carb_g": 59.9, "fibre_g": 16.3, "folate_ug": 625, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'moong_dal'),
  ('Green gram, whole', 'Sabut moong', 'pulse_legume',
   '{"kcal": 334, "protein_g": 24.0, "fat_g": 1.2, "carb_g": 56.7, "fibre_g": 16.3, "iron_mg": 6.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'moong_whole'),
  ('Red lentil, split (masoor dal)', 'Masoor dal', 'pulse_legume',
   '{"kcal": 343, "protein_g": 25.1, "fat_g": 1.1, "carb_g": 59.0, "fibre_g": 10.8, "folate_ug": 479, "iron_mg": 7.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'masoor_dal'),
  ('Bengal gram, split (chana dal)', 'Chana dal', 'pulse_legume',
   '{"kcal": 360, "protein_g": 21.0, "fat_g": 5.3, "carb_g": 57.0, "fibre_g": 12.0, "iron_mg": 5.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'chana_dal'),
  ('Chickpea, white (kabuli chana)', 'Kabuli chana', 'pulse_legume',
   '{"kcal": 364, "protein_g": 19.3, "fat_g": 6.0, "carb_g": 61.0, "fibre_g": 17.0, "folate_ug": 557, "iron_mg": 6.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'kabuli_chana'),
  ('Bengal gram, whole (kala chana)', 'Kala chana', 'pulse_legume',
   '{"kcal": 360, "protein_g": 20.0, "fat_g": 5.6, "carb_g": 58.0, "fibre_g": 17.0, "iron_mg": 5.8}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'kala_chana'),
  ('Kidney bean (rajma)', 'Rajma', 'pulse_legume',
   '{"kcal": 333, "protein_g": 23.6, "fat_g": 1.1, "carb_g": 60.0, "fibre_g": 15.2, "folate_ug": 394, "iron_mg": 8.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'rajma'),
  ('Black gram, split (urad dal)', 'Urad dal', 'pulse_legume',
   '{"kcal": 341, "protein_g": 24.0, "fat_g": 1.4, "carb_g": 59.0, "fibre_g": 13.0, "iron_mg": 7.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'urad_dal'),
  ('Cowpea (lobia / chawli)', 'Lobia', 'pulse_legume',
   '{"kcal": 343, "protein_g": 23.5, "fat_g": 1.3, "carb_g": 60.0, "fibre_g": 11.0, "iron_mg": 8.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'lobia'),
  ('Horse gram (kulthi)', 'Kulthi / Ulavalu', 'pulse_legume',
   '{"kcal": 321, "protein_g": 22.0, "fat_g": 0.5, "carb_g": 57.0, "fibre_g": 5.3, "iron_mg": 6.8}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'horse_gram'),
  ('Soyabean, dry', 'Soya', 'pulse_legume',
   '{"kcal": 432, "protein_g": 35.0, "fat_g": 19.9, "carb_g": 20.9, "fibre_g": 13.0, "calcium_mg": 277, "iron_mg": 15.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron', 'high_calcium']::text[], array['soy']::text[], 'india', 'PROVISIONAL', 'soyabean'),
  ('Dried green peas', 'Sukha matar', 'pulse_legume',
   '{"kcal": 341, "protein_g": 24.5, "fat_g": 1.2, "carb_g": 60.0, "fibre_g": 25.0, "iron_mg": 4.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'dried_peas'),
  ('Bengal gram flour (besan)', 'Besan', 'pulse_legume',
   '{"kcal": 387, "protein_g": 22.4, "fat_g": 6.7, "carb_g": 57.8, "fibre_g": 10.8, "folate_ug": 437, "iron_mg": 4.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'besan'),
  ('Green gram, sprouted', 'Ankurit moong', 'pulse_legume',
   '{"kcal": 30, "protein_g": 3.0, "fat_g": 0.2, "carb_g": 5.9, "fibre_g": 1.8, "vitamin_c_mg": 13.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sprouted_moong'),
  ('Moth bean (matki)', 'Matki', 'pulse_legume',
   '{"kcal": 343, "protein_g": 22.9, "fat_g": 1.6, "carb_g": 61.5, "fibre_g": 10.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'moth_bean'),
  -- nut_seed
  ('Almond', 'Badam', 'nut_seed',
   '{"kcal": 597, "protein_g": 20.8, "fat_g": 58.9, "carb_g": 10.5, "fibre_g": 12.5, "calcium_mg": 230, "iron_mg": 3.7, "magnesium_mg": 270}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron', 'high_calcium']::text[], array['tree_nut']::text[], 'india', 'PROVISIONAL', 'almond'),
  ('Cashew nut', 'Kaju', 'nut_seed',
   '{"kcal": 553, "protein_g": 18.2, "fat_g": 43.9, "carb_g": 30.2, "fibre_g": 3.3, "iron_mg": 6.7, "magnesium_mg": 292}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_iron']::text[], array['tree_nut']::text[], 'india', 'PROVISIONAL', 'cashew'),
  ('Walnut', 'Akhrot', 'nut_seed',
   '{"kcal": 654, "protein_g": 15.2, "fat_g": 65.2, "carb_g": 13.7, "fibre_g": 6.7, "magnesium_mg": 158}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], array['tree_nut']::text[], 'india', 'PROVISIONAL', 'walnut'),
  ('Groundnut', 'Moongphali', 'nut_seed',
   '{"kcal": 567, "protein_g": 25.8, "fat_g": 49.2, "carb_g": 16.1, "fibre_g": 8.5, "folate_ug": 240, "magnesium_mg": 168}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], array['peanut']::text[], 'india', 'PROVISIONAL', 'peanut'),
  ('Pistachio', 'Pista', 'nut_seed',
   '{"kcal": 560, "protein_g": 20.2, "fat_g": 45.3, "carb_g": 27.2, "fibre_g": 10.6, "iron_mg": 3.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], array['tree_nut']::text[], 'india', 'PROVISIONAL', 'pistachio'),
  ('Sesame seed', 'Til', 'nut_seed',
   '{"kcal": 573, "protein_g": 17.7, "fat_g": 49.7, "carb_g": 23.4, "fibre_g": 11.8, "calcium_mg": 975, "iron_mg": 14.6, "magnesium_mg": 351}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron', 'high_calcium']::text[], array['sesame']::text[], 'india', 'PROVISIONAL', 'sesame_seed'),
  ('Flax seed', 'Alsi', 'nut_seed',
   '{"kcal": 534, "protein_g": 18.3, "fat_g": 42.2, "carb_g": 28.9, "fibre_g": 27.3, "magnesium_mg": 392}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'flax_seed'),
  ('Chia seed', 'Chia', 'nut_seed',
   '{"kcal": 486, "protein_g": 16.5, "fat_g": 30.7, "carb_g": 42.1, "fibre_g": 34.4, "calcium_mg": 631, "iron_mg": 7.7, "magnesium_mg": 335}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'chia_seed'),
  ('Sunflower seed', 'Surajmukhi beej', 'nut_seed',
   '{"kcal": 584, "protein_g": 20.8, "fat_g": 51.5, "carb_g": 20.0, "fibre_g": 8.6, "magnesium_mg": 325}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'sunflower_seed'),
  ('Pumpkin seed', 'Kaddu ke beej', 'nut_seed',
   '{"kcal": 559, "protein_g": 30.2, "fat_g": 49.1, "carb_g": 10.7, "fibre_g": 6.0, "iron_mg": 8.8, "magnesium_mg": 592, "zinc_mg": 7.8}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_protein', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'pumpkin_seed'),
  ('Coconut, fresh kernel', 'Nariyal', 'nut_seed',
   '{"kcal": 354, "protein_g": 3.3, "fat_g": 33.5, "carb_g": 15.2, "fibre_g": 9.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'coconut_fresh'),
  ('Coconut, dry (copra)', 'Khopra', 'nut_seed',
   '{"kcal": 660, "protein_g": 6.9, "fat_g": 62.0, "carb_g": 25.0, "fibre_g": 16.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'coconut_dry'),
  -- vegetable
  ('Potato', 'Aloo', 'vegetable',
   '{"kcal": 77, "protein_g": 2.0, "fat_g": 0.1, "carb_g": 17.5, "fibre_g": 2.1, "potassium_mg": 425, "vitamin_c_mg": 19.7}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'potato'),
  ('Sweet potato', 'Shakarkandi', 'vegetable',
   '{"kcal": 86, "protein_g": 1.6, "fat_g": 0.1, "carb_g": 20.1, "fibre_g": 3.0, "vitamin_a_ug": 709}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sweet_potato'),
  ('Onion', 'Pyaz', 'vegetable',
   '{"kcal": 40, "protein_g": 1.1, "fat_g": 0.1, "carb_g": 9.3, "fibre_g": 1.7}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'onion'),
  ('Tomato, ripe', 'Tamatar', 'vegetable',
   '{"kcal": 18, "protein_g": 0.9, "fat_g": 0.2, "carb_g": 3.9, "fibre_g": 1.2, "vitamin_c_mg": 13.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'tomato'),
  ('Brinjal (aubergine)', 'Baingan', 'vegetable',
   '{"kcal": 25, "protein_g": 1.0, "fat_g": 0.2, "carb_g": 5.9, "fibre_g": 3.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'brinjal'),
  ('Okra (ladies finger)', 'Bhindi', 'vegetable',
   '{"kcal": 33, "protein_g": 1.9, "fat_g": 0.2, "carb_g": 7.5, "fibre_g": 3.2, "calcium_mg": 82, "folate_ug": 60}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'okra'),
  ('Bottle gourd', 'Lauki / Sorakaya', 'vegetable',
   '{"kcal": 14, "protein_g": 0.6, "fat_g": 0.1, "carb_g": 3.4, "fibre_g": 0.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'bottle_gourd'),
  ('Ridge gourd', 'Turai / Beerakaya', 'vegetable',
   '{"kcal": 20, "protein_g": 1.2, "fat_g": 0.2, "carb_g": 4.4, "fibre_g": 1.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'ridge_gourd'),
  ('Bitter gourd', 'Karela / Kakarakaya', 'vegetable',
   '{"kcal": 17, "protein_g": 1.0, "fat_g": 0.2, "carb_g": 3.7, "fibre_g": 2.8, "vitamin_c_mg": 84}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'bitter_gourd'),
  ('Pumpkin', 'Kaddu / Gummadikaya', 'vegetable',
   '{"kcal": 26, "protein_g": 1.0, "fat_g": 0.1, "carb_g": 6.5, "fibre_g": 0.5, "vitamin_a_ug": 426}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'pumpkin'),
  ('Cauliflower', 'Phool gobhi', 'vegetable',
   '{"kcal": 25, "protein_g": 1.9, "fat_g": 0.3, "carb_g": 5.0, "fibre_g": 2.0, "vitamin_c_mg": 48}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'cauliflower'),
  ('Cabbage', 'Patta gobhi', 'vegetable',
   '{"kcal": 25, "protein_g": 1.3, "fat_g": 0.1, "carb_g": 5.8, "fibre_g": 2.5, "vitamin_c_mg": 36}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'cabbage'),
  ('Carrot', 'Gajar', 'vegetable',
   '{"kcal": 41, "protein_g": 0.9, "fat_g": 0.2, "carb_g": 9.6, "fibre_g": 2.8, "vitamin_a_ug": 835}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'carrot'),
  ('Beetroot', 'Chukandar', 'vegetable',
   '{"kcal": 43, "protein_g": 1.6, "fat_g": 0.2, "carb_g": 9.6, "fibre_g": 2.8, "folate_ug": 109}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'beetroot'),
  ('Radish', 'Mooli', 'vegetable',
   '{"kcal": 16, "protein_g": 0.7, "fat_g": 0.1, "carb_g": 3.4, "fibre_g": 1.6}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'radish'),
  ('Capsicum, green', 'Shimla mirch', 'vegetable',
   '{"kcal": 20, "protein_g": 0.9, "fat_g": 0.2, "carb_g": 4.6, "fibre_g": 1.7, "vitamin_c_mg": 80}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'capsicum_green'),
  ('French beans', 'Farasbi', 'vegetable',
   '{"kcal": 31, "protein_g": 1.8, "fat_g": 0.1, "carb_g": 7.0, "fibre_g": 2.7}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'french_beans'),
  ('Cluster beans', 'Gawar / Goru chikkudu', 'vegetable',
   '{"kcal": 46, "protein_g": 3.2, "fat_g": 0.4, "carb_g": 10.8, "fibre_g": 3.2}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'cluster_beans'),
  ('Drumstick, pod', 'Sahjan / Munagakaya', 'vegetable',
   '{"kcal": 37, "protein_g": 2.1, "fat_g": 0.2, "carb_g": 8.5, "fibre_g": 3.2, "vitamin_c_mg": 141}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'drumstick_pod'),
  ('Mushroom, button', 'Khumb', 'vegetable',
   '{"kcal": 22, "protein_g": 3.1, "fat_g": 0.3, "carb_g": 3.3, "fibre_g": 1.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'mushroom_button'),
  ('Cucumber', 'Kheera', 'vegetable',
   '{"kcal": 15, "protein_g": 0.7, "fat_g": 0.1, "carb_g": 3.6, "fibre_g": 0.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'cucumber'),
  ('Ash gourd', 'Petha / Boodida gummadi', 'vegetable',
   '{"kcal": 13, "protein_g": 0.4, "fat_g": 0.2, "carb_g": 3.0, "fibre_g": 2.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'ash_gourd'),
  ('Colocasia root', 'Arbi / Chamagadda', 'vegetable',
   '{"kcal": 112, "protein_g": 1.5, "fat_g": 0.2, "carb_g": 26.5, "fibre_g": 4.1}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'colocasia'),
  ('Elephant foot yam', 'Suran / Kanda', 'vegetable',
   '{"kcal": 118, "protein_g": 1.5, "fat_g": 0.2, "carb_g": 27.9, "fibre_g": 4.1}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'elephant_yam'),
  ('Green peas, fresh', 'Hara matar', 'vegetable',
   '{"kcal": 81, "protein_g": 5.4, "fat_g": 0.4, "carb_g": 14.5, "fibre_g": 5.1, "folate_ug": 65, "vitamin_c_mg": 40}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'green_peas_fresh'),
  ('Sweet corn, fresh', 'Bhutta', 'vegetable',
   '{"kcal": 86, "protein_g": 3.3, "fat_g": 1.4, "carb_g": 19.0, "fibre_g": 2.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sweet_corn'),
  ('Broccoli', 'Broccoli', 'vegetable',
   '{"kcal": 34, "protein_g": 2.8, "fat_g": 0.4, "carb_g": 6.6, "fibre_g": 2.6, "folate_ug": 63, "vitamin_c_mg": 89}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'broccoli'),
  ('Ivy gourd', 'Tindora / Dondakaya', 'vegetable',
   '{"kcal": 18, "protein_g": 1.2, "fat_g": 0.1, "carb_g": 3.1, "fibre_g": 1.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'ivy_gourd'),
  ('Snake gourd', 'Chichinda / Potlakaya', 'vegetable',
   '{"kcal": 18, "protein_g": 0.5, "fat_g": 0.3, "carb_g": 3.3, "fibre_g": 0.8}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'snake_gourd'),
  ('Plantain, green (raw banana)', 'Kachcha kela / Aratikaya', 'vegetable',
   '{"kcal": 122, "protein_g": 1.3, "fat_g": 0.4, "carb_g": 31.9, "fibre_g": 2.3}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'raw_plantain'),
  ('Garlic', 'Lehsun', 'vegetable',
   '{"kcal": 149, "protein_g": 6.4, "fat_g": 0.5, "carb_g": 33.1, "fibre_g": 2.1}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'garlic'),
  ('Ginger, fresh', 'Adrak', 'vegetable',
   '{"kcal": 80, "protein_g": 1.8, "fat_g": 0.8, "carb_g": 17.8, "fibre_g": 2.0}'::jsonb,
   array['veg', 'vegan', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'ginger'),
  ('Green chilli', 'Hari mirch', 'vegetable',
   '{"kcal": 40, "protein_g": 1.9, "fat_g": 0.4, "carb_g": 8.8, "fibre_g": 1.5, "vitamin_c_mg": 143}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'green_chilli'),
  -- leafy_vegetable
  ('Spinach', 'Palak', 'leafy_vegetable',
   '{"kcal": 23, "protein_g": 2.9, "fat_g": 0.4, "carb_g": 3.6, "fibre_g": 2.2, "calcium_mg": 99, "folate_ug": 194, "iron_mg": 2.7, "vitamin_a_ug": 469}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'spinach'),
  ('Amaranth leaves', 'Chaulai / Thotakura', 'leafy_vegetable',
   '{"kcal": 23, "protein_g": 2.5, "fat_g": 0.3, "carb_g": 4.0, "fibre_g": 2.2, "calcium_mg": 215, "iron_mg": 2.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'amaranth_leaves'),
  ('Fenugreek leaves', 'Methi / Menthikura', 'leafy_vegetable',
   '{"kcal": 49, "protein_g": 4.4, "fat_g": 0.9, "carb_g": 6.0, "fibre_g": 1.1, "calcium_mg": 395, "iron_mg": 1.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'fenugreek_leaves'),
  ('Coriander leaves', 'Dhania / Kothimeera', 'leafy_vegetable',
   '{"kcal": 23, "protein_g": 2.1, "fat_g": 0.5, "carb_g": 3.7, "fibre_g": 2.8, "vitamin_c_mg": 27}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'coriander_leaves'),
  ('Curry leaves', 'Kadi patta / Karivepaku', 'leafy_vegetable',
   '{"kcal": 108, "protein_g": 6.1, "fat_g": 1.0, "carb_g": 18.7, "fibre_g": 6.4, "calcium_mg": 830, "iron_mg": 0.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'curry_leaves'),
  ('Mint leaves', 'Pudina', 'leafy_vegetable',
   '{"kcal": 44, "protein_g": 3.3, "fat_g": 0.7, "carb_g": 8.4, "fibre_g": 6.8, "iron_mg": 5.1}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'mint_leaves'),
  ('Mustard leaves', 'Sarson ka saag', 'leafy_vegetable',
   '{"kcal": 27, "protein_g": 2.9, "fat_g": 0.4, "carb_g": 4.7, "fibre_g": 3.2, "vitamin_c_mg": 70}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], array['mustard']::text[], 'india', 'PROVISIONAL', 'mustard_leaves'),
  ('Drumstick (moringa) leaves', 'Munagaku', 'leafy_vegetable',
   '{"kcal": 64, "protein_g": 9.4, "fat_g": 1.4, "carb_g": 8.3, "fibre_g": 2.0, "calcium_mg": 185, "iron_mg": 4.0, "vitamin_c_mg": 51}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_iron', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'drumstick_leaves'),
  -- fruit
  ('Banana', 'Kela', 'fruit',
   '{"kcal": 89, "protein_g": 1.1, "fat_g": 0.3, "carb_g": 22.8, "fibre_g": 2.6, "potassium_mg": 358}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'banana'),
  ('Apple, with skin', 'Seb', 'fruit',
   '{"kcal": 52, "protein_g": 0.3, "fat_g": 0.2, "carb_g": 13.8, "fibre_g": 2.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'apple'),
  ('Mango, ripe', 'Aam', 'fruit',
   '{"kcal": 60, "protein_g": 0.8, "fat_g": 0.4, "carb_g": 15.0, "fibre_g": 1.6, "vitamin_a_ug": 54, "vitamin_c_mg": 36}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'mango'),
  ('Papaya, ripe', 'Papita', 'fruit',
   '{"kcal": 43, "protein_g": 0.5, "fat_g": 0.3, "carb_g": 10.8, "fibre_g": 1.7, "vitamin_c_mg": 61}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'papaya'),
  ('Guava', 'Amrud / Jamakaya', 'fruit',
   '{"kcal": 68, "protein_g": 2.6, "fat_g": 0.9, "carb_g": 14.3, "fibre_g": 5.4, "vitamin_c_mg": 228}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'guava'),
  ('Orange', 'Santra', 'fruit',
   '{"kcal": 47, "protein_g": 0.9, "fat_g": 0.1, "carb_g": 11.8, "fibre_g": 2.4, "folate_ug": 30, "vitamin_c_mg": 53}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'orange'),
  ('Sweet lime', 'Mosambi', 'fruit',
   '{"kcal": 43, "protein_g": 0.8, "fat_g": 0.3, "carb_g": 9.3, "fibre_g": 0.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sweet_lime'),
  ('Grapes', 'Angoor', 'fruit',
   '{"kcal": 69, "protein_g": 0.7, "fat_g": 0.2, "carb_g": 18.1, "fibre_g": 0.9}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'grapes'),
  ('Pomegranate', 'Anar', 'fruit',
   '{"kcal": 83, "protein_g": 1.7, "fat_g": 1.2, "carb_g": 18.7, "fibre_g": 4.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'pomegranate'),
  ('Watermelon', 'Tarbooz', 'fruit',
   '{"kcal": 30, "protein_g": 0.6, "fat_g": 0.2, "carb_g": 7.6, "fibre_g": 0.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'watermelon'),
  ('Muskmelon', 'Kharbooja', 'fruit',
   '{"kcal": 34, "protein_g": 0.8, "fat_g": 0.2, "carb_g": 8.2, "fibre_g": 0.9, "vitamin_c_mg": 37}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'muskmelon'),
  ('Pineapple', 'Ananas', 'fruit',
   '{"kcal": 50, "protein_g": 0.5, "fat_g": 0.1, "carb_g": 13.1, "fibre_g": 1.4, "vitamin_c_mg": 48}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'pineapple'),
  ('Sapota (chikoo)', 'Chikoo', 'fruit',
   '{"kcal": 83, "protein_g": 0.4, "fat_g": 1.1, "carb_g": 20.0, "fibre_g": 5.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sapota'),
  ('Custard apple', 'Sitaphal', 'fruit',
   '{"kcal": 94, "protein_g": 2.1, "fat_g": 0.3, "carb_g": 23.6, "fibre_g": 4.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'custard_apple'),
  ('Jackfruit, ripe', 'Kathal / Panasa', 'fruit',
   '{"kcal": 95, "protein_g": 1.7, "fat_g": 0.6, "carb_g": 23.2, "fibre_g": 1.5}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'jackfruit'),
  ('Pear', 'Nashpati', 'fruit',
   '{"kcal": 57, "protein_g": 0.4, "fat_g": 0.1, "carb_g": 15.2, "fibre_g": 3.1}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'pear'),
  ('Plum', 'Aloo bukhara', 'fruit',
   '{"kcal": 46, "protein_g": 0.7, "fat_g": 0.3, "carb_g": 11.4, "fibre_g": 1.4}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'plum'),
  ('Litchi', 'Litchi', 'fruit',
   '{"kcal": 66, "protein_g": 0.8, "fat_g": 0.4, "carb_g": 16.5, "fibre_g": 1.3, "vitamin_c_mg": 72}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'litchi'),
  ('Strawberry', 'Strawberry', 'fruit',
   '{"kcal": 32, "protein_g": 0.7, "fat_g": 0.3, "carb_g": 7.7, "fibre_g": 2.0, "vitamin_c_mg": 59}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'strawberry'),
  ('Dates, dried', 'Khajoor', 'fruit',
   '{"kcal": 282, "protein_g": 2.5, "fat_g": 0.4, "carb_g": 75.0, "fibre_g": 8.0, "iron_mg": 1.0, "potassium_mg": 656}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre']::text[], '{}', 'india', 'PROVISIONAL', 'dates_dry'),
  ('Raisins', 'Kishmish', 'fruit',
   '{"kcal": 299, "protein_g": 3.1, "fat_g": 0.5, "carb_g": 79.2, "fibre_g": 3.7, "iron_mg": 1.9, "potassium_mg": 749}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'raisins'),
  ('Fig, dried', 'Anjeer', 'fruit',
   '{"kcal": 249, "protein_g": 3.3, "fat_g": 0.9, "carb_g": 63.9, "fibre_g": 9.8, "calcium_mg": 162, "iron_mg": 2.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free', 'high_fibre', 'high_calcium']::text[], '{}', 'india', 'PROVISIONAL', 'fig_dry'),
  ('Indian gooseberry', 'Amla / Usirikaya', 'fruit',
   '{"kcal": 44, "protein_g": 0.9, "fat_g": 0.6, "carb_g": 10.2, "fibre_g": 4.3}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'amla'),
  ('Lemon', 'Nimbu', 'fruit',
   '{"kcal": 29, "protein_g": 1.1, "fat_g": 0.3, "carb_g": 9.3, "fibre_g": 2.8, "vitamin_c_mg": 53}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'lemon'),
  -- dairy
  ('Cow milk, whole', 'Gaay ka doodh', 'dairy',
   '{"kcal": 61, "protein_g": 3.2, "fat_g": 3.3, "carb_g": 4.8, "fibre_g": 0.0, "b12_ug": 0.4, "calcium_mg": 120}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'cow_milk_whole'),
  ('Buffalo milk', 'Bhains ka doodh', 'dairy',
   '{"kcal": 97, "protein_g": 3.8, "fat_g": 6.9, "carb_g": 5.2, "fibre_g": 0.0, "calcium_mg": 169}'::jsonb,
   array['veg', 'gluten_free', 'high_calcium']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'buffalo_milk'),
  ('Toned milk', 'Toned doodh', 'dairy',
   '{"kcal": 58, "protein_g": 3.1, "fat_g": 3.0, "carb_g": 4.7, "fibre_g": 0.0, "calcium_mg": 120}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'toned_milk'),
  ('Skimmed milk', 'Skimmed doodh', 'dairy',
   '{"kcal": 35, "protein_g": 3.4, "fat_g": 0.1, "carb_g": 5.0, "fibre_g": 0.0, "b12_ug": 0.5, "calcium_mg": 122}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'skimmed_milk'),
  ('Curd (dahi), whole milk', 'Dahi / Perugu', 'dairy',
   '{"kcal": 60, "protein_g": 3.5, "fat_g": 3.3, "carb_g": 4.7, "fibre_g": 0.0, "b12_ug": 0.4, "calcium_mg": 120}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'curd_whole'),
  ('Paneer', 'Paneer', 'dairy',
   '{"kcal": 265, "protein_g": 18.3, "fat_g": 20.8, "carb_g": 1.2, "fibre_g": 0.0, "calcium_mg": 208}'::jsonb,
   array['veg', 'gluten_free', 'high_protein', 'high_calcium']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'paneer'),
  ('Cheese, processed', 'Cheese', 'dairy',
   '{"kcal": 350, "protein_g": 22.0, "fat_g": 28.0, "carb_g": 2.0, "fibre_g": 0.0, "calcium_mg": 700}'::jsonb,
   array['veg', 'gluten_free', 'high_protein', 'high_calcium']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'cheese_processed'),
  ('Butter', 'Makkhan', 'dairy',
   '{"kcal": 717, "protein_g": 0.9, "fat_g": 81.1, "carb_g": 0.1, "fibre_g": 0.0}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'butter'),
  ('Ghee', 'Ghee', 'dairy',
   '{"kcal": 900, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'ghee'),
  ('Khoa (mawa)', 'Khoya', 'dairy',
   '{"kcal": 421, "protein_g": 14.6, "fat_g": 31.2, "carb_g": 20.5, "fibre_g": 0.0, "calcium_mg": 650}'::jsonb,
   array['veg', 'gluten_free', 'high_calcium']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'khoa'),
  ('Buttermilk (chaas)', 'Chaas / Majjiga', 'dairy',
   '{"kcal": 40, "protein_g": 3.3, "fat_g": 0.9, "carb_g": 4.8, "fibre_g": 0.0, "calcium_mg": 116}'::jsonb,
   array['veg', 'gluten_free']::text[], array['milk']::text[], 'india', 'PROVISIONAL', 'buttermilk'),
  -- egg
  ('Egg, hen, whole', 'Anda', 'egg',
   '{"kcal": 155, "protein_g": 12.6, "fat_g": 10.6, "carb_g": 1.1, "fibre_g": 0.0, "b12_ug": 1.1, "vitamin_d_ug": 2.0}'::jsonb,
   array['egg', 'gluten_free']::text[], array['egg']::text[], 'india', 'PROVISIONAL', 'egg_whole'),
  ('Egg white', 'Ande ka safed bhag', 'egg',
   '{"kcal": 52, "protein_g": 10.9, "fat_g": 0.2, "carb_g": 0.7, "fibre_g": 0.0}'::jsonb,
   array['egg', 'gluten_free']::text[], array['egg']::text[], 'india', 'PROVISIONAL', 'egg_white'),
  ('Egg yolk', 'Ande ki zardi', 'egg',
   '{"kcal": 322, "protein_g": 15.9, "fat_g": 26.5, "carb_g": 3.6, "fibre_g": 0.0, "b12_ug": 1.9, "vitamin_d_ug": 5.4}'::jsonb,
   array['egg', 'gluten_free', 'high_protein']::text[], array['egg']::text[], 'india', 'PROVISIONAL', 'egg_yolk'),
  -- meat_poultry
  ('Chicken breast, skinless', 'Murgi ka seena', 'meat_poultry',
   '{"kcal": 165, "protein_g": 31.0, "fat_g": 3.6, "carb_g": 0.0, "fibre_g": 0.0, "b12_ug": 0.3}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], '{}', 'india', 'PROVISIONAL', 'chicken_breast'),
  ('Chicken, whole with skin', 'Murgi', 'meat_poultry',
   '{"kcal": 215, "protein_g": 18.6, "fat_g": 15.1, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], '{}', 'india', 'PROVISIONAL', 'chicken_whole'),
  ('Goat meat (mutton)', 'Bakra gosht', 'meat_poultry',
   '{"kcal": 143, "protein_g": 27.1, "fat_g": 3.0, "carb_g": 0.0, "fibre_g": 0.0, "b12_ug": 1.2, "iron_mg": 3.7, "zinc_mg": 4.5}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'goat_mutton'),
  ('Goat liver', 'Kaleji', 'meat_poultry',
   '{"kcal": 139, "protein_g": 20.4, "fat_g": 4.7, "carb_g": 2.6, "fibre_g": 0.0, "iron_mg": 6.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein', 'high_iron']::text[], '{}', 'india', 'PROVISIONAL', 'goat_liver'),
  -- fish_seafood
  ('Rohu (fish)', 'Rohu', 'fish_seafood',
   '{"kcal": 97, "protein_g": 16.6, "fat_g": 1.4, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'rohu'),
  ('Pomfret (fish)', 'Paplet', 'fish_seafood',
   '{"kcal": 96, "protein_g": 20.0, "fat_g": 1.3, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'pomfret'),
  ('Seer fish (surmai)', 'Surmai / Vanjaram', 'fish_seafood',
   '{"kcal": 105, "protein_g": 21.0, "fat_g": 2.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'kingfish'),
  ('Sardine, canned in oil, drained', 'Sardine', 'fish_seafood',
   '{"kcal": 208, "protein_g": 24.6, "fat_g": 11.5, "carb_g": 0.0, "fibre_g": 0.0, "b12_ug": 8.9, "calcium_mg": 382, "vitamin_d_ug": 4.8}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein', 'high_calcium']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'sardine_canned'),
  ('Mackerel (bangda)', 'Bangda', 'fish_seafood',
   '{"kcal": 205, "protein_g": 18.6, "fat_g": 13.9, "carb_g": 0.0, "fibre_g": 0.0, "b12_ug": 8.7, "vitamin_d_ug": 16.1}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['fish']::text[], 'india', 'PROVISIONAL', 'mackerel'),
  ('Prawn', 'Jhinga / Royya', 'fish_seafood',
   '{"kcal": 99, "protein_g": 24.0, "fat_g": 0.3, "carb_g": 0.2, "fibre_g": 0.0, "b12_ug": 1.1}'::jsonb,
   array['non_veg', 'gluten_free', 'high_protein']::text[], array['shellfish']::text[], 'india', 'PROVISIONAL', 'prawn'),
  -- oil_fat
  ('Groundnut oil', 'Moongphali ka tel', 'oil_fat',
   '{"kcal": 884, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], array['peanut']::text[], 'india', 'PROVISIONAL', 'groundnut_oil'),
  ('Mustard oil', 'Sarson ka tel', 'oil_fat',
   '{"kcal": 884, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], array['mustard']::text[], 'india', 'PROVISIONAL', 'mustard_oil'),
  ('Coconut oil', 'Nariyal tel', 'oil_fat',
   '{"kcal": 862, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'coconut_oil'),
  ('Sunflower oil', 'Surajmukhi tel', 'oil_fat',
   '{"kcal": 884, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sunflower_oil'),
  ('Sesame oil (gingelly)', 'Til ka tel', 'oil_fat',
   '{"kcal": 884, "protein_g": 0.0, "fat_g": 100.0, "carb_g": 0.0, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], array['sesame']::text[], 'india', 'PROVISIONAL', 'sesame_oil'),
  -- sugar_sweetener
  ('Sugar, white', 'Cheeni', 'sugar_sweetener',
   '{"kcal": 387, "protein_g": 0.0, "fat_g": 0.0, "carb_g": 99.8, "fibre_g": 0.0}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'sugar'),
  ('Jaggery', 'Gud / Bellam', 'sugar_sweetener',
   '{"kcal": 383, "protein_g": 0.4, "fat_g": 0.1, "carb_g": 97.0, "fibre_g": 0.0, "iron_mg": 2.6}'::jsonb,
   array['veg', 'vegan', 'jain', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'jaggery'),
  ('Honey', 'Shahad', 'sugar_sweetener',
   '{"kcal": 304, "protein_g": 0.3, "fat_g": 0.0, "carb_g": 82.4, "fibre_g": 0.2}'::jsonb,
   array['veg', 'gluten_free']::text[], '{}', 'india', 'PROVISIONAL', 'honey')
on conflict (source, source_id) do nothing;


-- ============================================================================
-- CHECKS
-- ============================================================================

-- 1. How many foods loaded, and how many are still provisional.
select count(*) as foods_loaded,
       count(*) filter (where source = 'PROVISIONAL') as still_provisional
from public.foods;

-- 2. Foods by group.
select food_group, count(*) as n
from public.foods
group by food_group
order by food_group;

-- 3. Every food must have the five core nutrients. This must return 0 rows.
select name
from public.foods
where not (per_100g ?& array['kcal', 'protein_g', 'fat_g', 'carb_g', 'fibre_g']);

-- 4. Example of the candidate list the planner asks for: vegetarian,
--    high-iron, no peanut allergy.
select name, per_100g ->> 'iron_mg' as iron_mg
from public.foods
where diet_flags @> array['veg']::text[]
  and diet_flags @> array['high_iron']::text[]
  and not (allergens && array['peanut']::text[])
order by (per_100g ->> 'iron_mg')::numeric desc;
