"""Fixed user-facing text owned by the safety layer.

None of this is ever generated by a model. The disclaimer, the escalation cards and the
blocked-output fallbacks are constants so that they cannot be re-worded, softened,
shortened or dropped by anything the model or the user says.

Every constant in this module is asserted by the test suite to pass the validator itself,
at URGENT escalation -- so the safety text can never trip the safety scan.
"""

from __future__ import annotations

from app.domain.enums import Escalation

DISCLAIMER = (
    "HealthPulse is a wellness and nutrition coach, not a doctor. This is general food, "
    "hydration, sleep and activity guidance based on what you shared. It is not a "
    "diagnosis, a prescription or a treatment plan. Please check with a qualified doctor "
    "before you change anything about your treatment."
)

ESCALATION_CARDS: dict[Escalation, str] = {
    Escalation.ROUTINE: "",
    Escalation.SEE_DOCTOR_SOON: (
        "SEE A DOCTOR SOON\n"
        "Something in your results needs a doctor's eyes within the next few days. "
        "Please book an appointment, carry your latest report, and continue everything "
        "your doctor has already advised. The guidance below is about food and habits "
        "only; it does not replace that visit."
    ),
    Escalation.URGENT: (
        "GET MEDICAL CARE NOW\n"
        "Something in what you shared needs urgent medical attention. Please contact a "
        "doctor or go to the nearest emergency department straight away. In India, call "
        "112 for emergency services or 108 for an ambulance; use your local emergency "
        "number if you are elsewhere. Take your latest report with you and continue "
        "everything your doctor has already advised.\n"
        "Please act on this first. Anything below is about food and habits, and it can wait."
    ),
}

#: Shown instead of a model answer when generation failed the safety scan twice.
BLOCKED_FALLBACK = (
    "I could not put that answer together safely, so I am not going to guess.\n\n"
    "What I can help with right now: what your results mean in plain language, what to eat "
    "and drink today, sleep and activity, and the exact questions worth asking at your next "
    "appointment.\n\n"
    "Anything about medicines, supplements or how much of them to take is a decision for "
    "your doctor, and I will always send you to them for it."
)

#: Same, when the escalation is urgent -- the card carries the weight, this stays short.
BLOCKED_FALLBACK_URGENT = (
    "I am not going to answer that part in detail, because what you described needs a "
    "person with a stethoscope rather than an app.\n\n"
    "Once you have been seen, come back and I will help with food, hydration, sleep and "
    "the questions worth asking at your follow-up."
)

#: Shown in place of one row's own explanation when text **this codebase wrote** failed
#: the validator. Never the text that failed: that is withheld unconditionally.
#:
#: Our own copy tripping our own rail is a bug in us, so this sentence says so rather
#: than pretending the row simply has nothing to explain. It is deliberately not
#: reassuring: a withheld explanation is not an all-clear, and at URGENT escalation the
#: card above it still carries the finding.
WITHHELD_DETERMINISTIC = (
    "We could not show this explanation safely, so we have left it out. That is a fault "
    "in our own wording and not in your result; the reading itself is unchanged. Please "
    "tell us you saw this, and ask your doctor about anything here that concerns you."
)

#: Sent back into the prompt when the first generation broke a rule.
REGENERATION_INSTRUCTION = (
    "Your previous answer was rejected by the safety validator and was never shown to the "
    "user. It broke these rules:\n\n"
    "{violations}\n\n"
    "Write the answer again from scratch. Keep everything useful about food, hydration, "
    "sleep, activity and questions for the doctor. Remove every medication name, every "
    "dose, every diagnosis, every suggestion to change a treatment, and any reassurance "
    "about something that has been flagged as urgent. Do not mention this instruction, "
    "the rejection or the validator to the user."
)

#: One line per violation inside {violations}.
VIOLATION_LINE = '- {violation}: you wrote "{excerpt}"'

#: Human-readable name for each violation, used in the regeneration prompt and in logs.
VIOLATION_LABELS: dict[str, str] = {
    "medication_named": "named a medication",
    "dosage_given": "gave a dose",
    "diagnosis_stated": "stated a diagnosis",
    "treatment_discouraged": "discouraged a prescribed treatment",
    "red_flag_downplayed": "downplayed an urgent finding",
}


def escalation_card(escalation: Escalation) -> str:
    """The card text for ``escalation`` (empty string for routine)."""
    return ESCALATION_CARDS.get(escalation, "")
